// Auto-generated by ChiCom backend — do not edit
window.TOPIC_COLORS = [
  "oklch(0.62 0.15 260)",
  "oklch(0.62 0.15 25)",
  "oklch(0.62 0.15 155)",
  "oklch(0.62 0.15 60)",
  "oklch(0.62 0.15 320)",
  "oklch(0.62 0.15 200)",
  "oklch(0.62 0.15 90)",
  "oklch(0.62 0.15 290)",
  "oklch(0.62 0.15 0)"
];

window.ChiComData = (() => {
  const SOA_GROUPS = [
  {
    "id": "soa1",
    "name": "Amazon Sellers Viet Nam",
    "short": "Amazon Sellers VN",
    "type": "SOA"
  },
  {
    "id": "soa2",
    "name": "Cộng đồng Amazon Sellers VN",
    "short": "CĐ Amazon Sellers",
    "type": "SOA"
  }
];
  const EC_GROUPS  = [
  {
    "id": "ec1",
    "name": "Cộng Đồng MMO",
    "short": "MMO",
    "type": "EC"
  },
  {
    "id": "ec2",
    "name": "Cuồng Phong Hội (Crossborder CBEC)",
    "short": "Cuồng Phong Hội",
    "type": "EC"
  },
  {
    "id": "ec3",
    "name": "Cộng Đồng Dropshipping & Shopify VN",
    "short": "Dropship & Shopify",
    "type": "EC"
  },
  {
    "id": "ec4",
    "name": "Chuyện Nhà Bán (Shopee/TikTok)",
    "short": "Chuyện Nhà Bán",
    "type": "EC"
  },
  {
    "id": "ec5",
    "name": "Etsy To Go",
    "short": "Etsy To Go",
    "type": "EC"
  },
  {
    "id": "ec6",
    "name": "Etsy E-Z Cộng Đồng Etsy Việt",
    "short": "Etsy E-Z",
    "type": "EC"
  },
  {
    "id": "ec7",
    "name": "Cộng đồng ETSY Việt Nam",
    "short": "ETSY VN",
    "type": "EC"
  }
];
  const ALL_GROUPS = [...SOA_GROUPS, ...EC_GROUPS];
  const MASTER_TOPICS       = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance"
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges"
  }
];
  const Q1_WEIGHTS          = {
  "mt1": {
    "soa1": 19.2,
    "soa2": 37.5,
    "ec1": 14.8,
    "ec2": 7.0,
    "ec3": 14.0,
    "ec4": 21.3,
    "ec5": 11.6,
    "ec6": 3.8,
    "ec7": 7.7
  },
  "mt2": {
    "soa1": 0.7,
    "soa2": 0.8,
    "ec1": 1.8,
    "ec2": 0.0,
    "ec3": 1.0,
    "ec4": 1.7,
    "ec5": 0.5,
    "ec6": 0.0,
    "ec7": 0.7
  },
  "mt3": {
    "soa1": 25.3,
    "soa2": 26.9,
    "ec1": 8.4,
    "ec2": 0.7,
    "ec3": 4.0,
    "ec4": 8.0,
    "ec5": 20.3,
    "ec6": 13.5,
    "ec7": 27.1
  },
  "mt4": {
    "soa1": 5.9,
    "soa2": 1.2,
    "ec1": 1.4,
    "ec2": 9.6,
    "ec3": 1.7,
    "ec4": 0.4,
    "ec5": 3.1,
    "ec6": 0.0,
    "ec7": 1.1
  },
  "mt5": {
    "soa1": 8.7,
    "soa2": 3.5,
    "ec1": 7.0,
    "ec2": 0.5,
    "ec3": 12.0,
    "ec4": 6.6,
    "ec5": 19.9,
    "ec6": 24.5,
    "ec7": 17.1
  },
  "mt6": {
    "soa1": 16.0,
    "soa2": 6.9,
    "ec1": 1.3,
    "ec2": 33.1,
    "ec3": 18.7,
    "ec4": 26.5,
    "ec5": 10.5,
    "ec6": 29.5,
    "ec7": 19.4
  },
  "mt7": {
    "soa1": 5.9,
    "soa2": 11.2,
    "ec1": 9.4,
    "ec2": 41.7,
    "ec3": 37.0,
    "ec4": 14.1,
    "ec5": 20.6,
    "ec6": 22.3,
    "ec7": 16.8
  },
  "mt8": {
    "soa1": 17.9,
    "soa2": 11.2,
    "ec1": 2.1,
    "ec2": 7.2,
    "ec3": 10.1,
    "ec4": 20.6,
    "ec5": 7.9,
    "ec6": 5.7,
    "ec7": 10.0
  },
  "mt9": {
    "soa1": 0.0,
    "soa2": 0.0,
    "ec1": 0.0,
    "ec2": 0.0,
    "ec3": 0.0,
    "ec4": 0.0,
    "ec5": 0.0,
    "ec6": 0.0,
    "ec7": 0.0
  }
};
  const Q1_MASTER           = [
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border",
    "weight": 19.9,
    "color": "oklch(0.62 0.15 90)"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance",
    "weight": 18.0,
    "color": "oklch(0.62 0.15 200)"
  },
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support",
    "weight": 15.2,
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management",
    "weight": 14.9,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment",
    "weight": 11.1,
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization",
    "weight": 10.3,
    "color": "oklch(0.62 0.15 290)"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services",
    "weight": 2.7,
    "color": "oklch(0.62 0.15 60)"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud",
    "weight": 0.8,
    "color": "oklch(0.62 0.15 25)"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges",
    "weight": 0.0,
    "color": "oklch(0.62 0.15 0)"
  }
];
  const SUBTOPICS           = {
  "mt1": [
    "Chia sẻ chiến lược Amazon",
    "Kinh nghiệm launch SP mới",
    "Hỗ trợ seller mới bắt đầu",
    "Networking seller VN"
  ],
  "mt2": [
    "Cảnh báo scam Amazon",
    "Lừa đảo PPC agency",
    "Rủi ro suspension",
    "Phishing & hijack"
  ],
  "mt3": [
    "Tạo & verify tài khoản",
    "Health score & metrics",
    "Tool quản lý listing",
    "Xử lý A-Z claim"
  ],
  "mt4": [
    "Brand registry",
    "Kế toán US",
    "Pháp lý LLC",
    "Trademark & IP"
  ],
  "mt5": [
    "FBA vs FBM",
    "Forwarder VN→US",
    "Cước vận chuyển",
    "Kho 3PL ở Mỹ"
  ],
  "mt6": [
    "Payoneer & tài khoản US",
    "Thẻ Visa virtual",
    "Quy đổi USD→VND",
    "Hoàn thuế VAT EU"
  ],
  "mt7": [
    "TMĐT xuyên biên giới",
    "Dropshipping CBEC",
    "Nguồn hàng TQ",
    "Thủ tục XNK"
  ],
  "mt8": [
    "PPC optimization",
    "SEO listing",
    "A/B test main image",
    "Tối ưu CVR"
  ],
  "mt9": [
    "Khóa học mentor",
    "Thử thách 30 ngày",
    "Bootcamp PPC",
    "Coaching 1-1"
  ]
};
  const PERSONAS            = [
  {
    "id": "p_seller_az",
    "short": "Seller",
    "segment": "Amazon",
    "vn": "Seller (Amazon)"
  },
  {
    "id": "p_prospect_az",
    "short": "Prospect",
    "segment": "Amazon",
    "vn": "Prospect (Amazon)"
  },
  {
    "id": "p_svc_az",
    "short": "Service Provider",
    "segment": "Amazon",
    "vn": "Service Provider (Amazon)"
  },
  {
    "id": "p_svc_cbec",
    "short": "Service Provider",
    "segment": "CBEC",
    "vn": "Service Provider (CBEC)"
  },
  {
    "id": "p_prospect_ot",
    "short": "Prospect",
    "segment": "Others",
    "vn": "Prospect (Others)"
  },
  {
    "id": "p_seller_ot",
    "short": "Seller",
    "segment": "Others",
    "vn": "Seller (Others)"
  }
];
  const Q2_MATRIX           = {
  "mt1": {
    "p_seller_az": 1473,
    "p_prospect_az": 333,
    "p_svc_az": 385,
    "p_svc_cbec": 527,
    "p_prospect_ot": 990,
    "p_seller_ot": 2979
  },
  "mt2": {
    "p_seller_az": 16,
    "p_prospect_az": 25,
    "p_svc_az": 0,
    "p_svc_cbec": 4,
    "p_prospect_ot": 118,
    "p_seller_ot": 243
  },
  "mt3": {
    "p_seller_az": 3024,
    "p_prospect_az": 570,
    "p_svc_az": 103,
    "p_svc_cbec": 151,
    "p_prospect_ot": 942,
    "p_seller_ot": 2156
  },
  "mt4": {
    "p_seller_az": 2,
    "p_prospect_az": 25,
    "p_svc_az": 88,
    "p_svc_cbec": 284,
    "p_prospect_ot": 81,
    "p_seller_ot": 70
  },
  "mt5": {
    "p_seller_az": 34,
    "p_prospect_az": 20,
    "p_svc_az": 129,
    "p_svc_cbec": 3027,
    "p_prospect_ot": 655,
    "p_seller_ot": 873
  },
  "mt6": {
    "p_seller_az": 935,
    "p_prospect_az": 230,
    "p_svc_az": 11,
    "p_svc_cbec": 318,
    "p_prospect_ot": 2628,
    "p_seller_ot": 3397
  },
  "mt7": {
    "p_seller_az": 61,
    "p_prospect_az": 36,
    "p_svc_az": 11,
    "p_svc_cbec": 2143,
    "p_prospect_ot": 2767,
    "p_seller_ot": 2331
  },
  "mt8": {
    "p_seller_az": 980,
    "p_prospect_az": 647,
    "p_svc_az": 39,
    "p_svc_cbec": 140,
    "p_prospect_ot": 900,
    "p_seller_ot": 2462
  },
  "mt9": {
    "p_seller_az": 0,
    "p_prospect_az": 0,
    "p_svc_az": 0,
    "p_svc_cbec": 0,
    "p_prospect_ot": 0,
    "p_seller_ot": 0
  }
};
  const Q3_SELLER_PROSPECT  = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support",
    "seller": 4452,
    "prospect": 1323,
    "sellerPct": 21.2,
    "prospectPct": 12.1,
    "diff": 9.1
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud",
    "seller": 259,
    "prospect": 143,
    "sellerPct": 1.2,
    "prospectPct": 1.3,
    "diff": -0.1
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management",
    "seller": 5180,
    "prospect": 1512,
    "sellerPct": 24.6,
    "prospectPct": 13.8,
    "diff": 10.8
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services",
    "seller": 72,
    "prospect": 106,
    "sellerPct": 0.3,
    "prospectPct": 1.0,
    "diff": -0.7
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment",
    "seller": 907,
    "prospect": 675,
    "sellerPct": 4.3,
    "prospectPct": 6.2,
    "diff": -1.9
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance",
    "seller": 4332,
    "prospect": 2858,
    "sellerPct": 20.6,
    "prospectPct": 26.1,
    "diff": -5.5
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border",
    "seller": 2392,
    "prospect": 2803,
    "sellerPct": 11.4,
    "prospectPct": 25.6,
    "diff": -14.2
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization",
    "seller": 3442,
    "prospect": 1547,
    "sellerPct": 16.4,
    "prospectPct": 14.1,
    "diff": 2.3
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges",
    "seller": 0,
    "prospect": 0,
    "sellerPct": 0.0,
    "prospectPct": 0.0,
    "diff": 0.0
  }
];
  const Q3_SUBS             = [
  {
    "vn": "Kinh doanh xuất nhập khẩu và bán hàng quốc tế",
    "seller": 8.7,
    "prospect": 15.92,
    "diff": -7.22
  },
  {
    "vn": "Thuế và Chi phí Kinh doanh trên Amazon cho Seller Việt Nam",
    "seller": 10.66,
    "prospect": 12.19,
    "diff": -1.53
  },
  {
    "vn": "Bán hàng và vận hành kinh doanh trên Amazon",
    "seller": 12.49,
    "prospect": 8.91,
    "diff": 3.58
  },
  {
    "vn": "Vấn đề xác minh, khoá, rủi ro tài khoản Amazon",
    "seller": 10.03,
    "prospect": 7.61,
    "diff": 2.42
  },
  {
    "vn": "Vận hành tài khoản và thanh toán quốc tế cho seller",
    "seller": 4.7,
    "prospect": 10.35,
    "diff": -5.65
  },
  {
    "vn": "Dịch vụ vận chuyển và fulfillment",
    "seller": 4.22,
    "prospect": 5.88,
    "diff": -1.66
  },
  {
    "vn": "Chia sẻ, học hỏi và hợp tác kinh nghiệm bán hàng Amazon",
    "seller": 6.32,
    "prospect": 1.98,
    "diff": 4.34
  },
  {
    "vn": "Khó khăn và thách thức khi bán hàng trên Amazon",
    "seller": 6.45,
    "prospect": 0.59,
    "diff": 5.86
  },
  {
    "vn": "Sự kiện, đào tạo và kết nối cộng đồng bán hàng Amazon",
    "seller": 2.46,
    "prospect": 2.03,
    "diff": 0.43
  },
  {
    "vn": "Hướng dẫn và hỗ trợ khởi đầu bán hàng Amazon",
    "seller": 0.06,
    "prospect": 4.09,
    "diff": -4.03
  },
  {
    "vn": "Dịch vụ hỗ trợ và xử lý tài khoản Amazon",
    "seller": 2.16,
    "prospect": 1.86,
    "diff": 0.3
  },
  {
    "vn": "Kinh nghiệm và chiến lược bán hàng trên Amazon",
    "seller": 2.36,
    "prospect": 0.42,
    "diff": 1.94
  },
  {
    "vn": "Hợp tác, hỗ trợ và vận hành bán hàng Amazon",
    "seller": 1.16,
    "prospect": 1.38,
    "diff": -0.22
  },
  {
    "vn": "Cảnh báo rủi ro và lừa đảo khi kinh doanh Amazon",
    "seller": 1.27,
    "prospect": 1.26,
    "diff": 0.01
  },
  {
    "vn": "Thanh toán và rút tiền Amazon qua Payoneer/PingPong",
    "seller": 1.25,
    "prospect": 1.22,
    "diff": 0.03
  },
  {
    "vn": "Dịch vụ và giải pháp pháp lý, thương hiệu và công cụ kinh doanh cho người bán Amazon",
    "seller": 0.34,
    "prospect": 0.92,
    "diff": -0.58
  },
  {
    "vn": "Kinh doanh Amazon FBA và FBM: vận hành & tối ưu chi phí",
    "seller": 0.21,
    "prospect": 0.11,
    "diff": 0.1
  },
  {
    "vn": "Vấn đề không nhận được mã OTP Amazon",
    "seller": 0.06,
    "prospect": 0.09,
    "diff": -0.03
  },
  {
    "vn": "Dịch vụ và giải pháp pháp lý, thương hiệu và công cụ cho Seller Amazon",
    "seller": 0.0,
    "prospect": 0.03,
    "diff": -0.03
  },
  {
    "vn": "Ưu đãi giảm giá Helium10 cho người bán Amazon",
    "seller": 0.0,
    "prospect": 0.01,
    "diff": -0.01
  },
  {
    "vn": "Vấn đề xác minh, khoá, rủi ko Amazon",
    "seller": 0.0,
    "prospect": 0.01,
    "diff": -0.01
  },
  {
    "vn": "Chiến lược, kinh nghiệm và hỗ trợ cộng đồng bán hàng Amazon",
    "seller": 0.0,
    "prospect": 0.01,
    "diff": -0.01
  },
  {
    "vn": "Hỏi đáp và hỗ trợ cộng đồng bán hàng",
    "seller": 0.01,
    "prospect": 0.0,
    "diff": 0.01
  },
  {
    "vn": "Hỗ trợ khởi đầu bán hàng Amazon",
    "seller": 0.0,
    "prospect": 0.0,
    "diff": 0.0
  }
];
  const MONTHS              = [
  "2025-12",
  "2026-01",
  "2026-02",
  "2026-03",
  "2026-04"
];
  const Q4_TRENDS           = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "points": [
      149,
      2280,
      1759,
      2447,
      58
    ],
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "points": [
      5,
      187,
      70,
      140,
      4
    ],
    "color": "oklch(0.62 0.15 25)"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "points": [
      185,
      2122,
      1867,
      2492,
      280
    ],
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "points": [
      4,
      168,
      106,
      249,
      24
    ],
    "color": "oklch(0.62 0.15 60)"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "points": [
      80,
      1504,
      916,
      2100,
      138
    ],
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "points": [
      252,
      1782,
      2061,
      3233,
      191
    ],
    "color": "oklch(0.62 0.15 200)"
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "points": [
      175,
      1761,
      1702,
      3486,
      225
    ],
    "color": "oklch(0.62 0.15 90)"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "points": [
      176,
      1353,
      1194,
      2294,
      151
    ],
    "color": "oklch(0.62 0.15 290)"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "points": [
      0,
      0,
      0,
      0,
      0
    ],
    "color": "oklch(0.62 0.15 0)"
  }
];
  const WEEKS               = [
  "Dec 22",
  "Dec 29",
  "Jan 5",
  "Jan 12",
  "Jan 19",
  "Jan 26",
  "Feb 2",
  "Feb 9",
  "Feb 16",
  "Feb 23",
  "Mar 2",
  "Mar 9",
  "Mar 16",
  "Mar 23",
  "Mar 30",
  "Apr 6"
];
  const Q4_EVENTS           = [
  {
    "week": 11,
    "label": "Spike Mar 9 · +68%"
  },
  {
    "week": 12,
    "label": "Spike Mar 16 · +70%"
  },
  {
    "week": 13,
    "label": "Spike Mar 23 · +56%"
  }
];
  const Q4_WEEKLY           = [
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "color": "oklch(0.62 0.15 200)",
    "points": [
      3,
      420,
      415,
      432,
      301,
      514,
      634,
      524,
      221,
      695,
      694,
      1015,
      642,
      747,
      253,
      9
    ]
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "color": "oklch(0.62 0.15 90)",
    "points": [
      22,
      307,
      592,
      430,
      320,
      306,
      412,
      364,
      231,
      710,
      680,
      941,
      900,
      800,
      319,
      15
    ]
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "color": "oklch(0.62 0.15 155)",
    "points": [
      6,
      411,
      644,
      461,
      383,
      429,
      464,
      417,
      440,
      543,
      411,
      543,
      611,
      747,
      422,
      14
    ]
  },
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "color": "oklch(0.62 0.15 260)",
    "points": [
      7,
      447,
      475,
      434,
      514,
      605,
      455,
      495,
      419,
      393,
      560,
      635,
      518,
      553,
      178,
      5
    ]
  }
];
  const DAYS_VN             = [
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "CN"
];
  const DAYS_EN             = [
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun"
];
  const Q56_HEATMAP         = [
  [
    35,
    13,
    8,
    16,
    4,
    7,
    17,
    44,
    58,
    67,
    98,
    101,
    82,
    48,
    59,
    79,
    81,
    46,
    47,
    46,
    86,
    78,
    30,
    24
  ],
  [
    21,
    5,
    9,
    5,
    6,
    7,
    13,
    56,
    74,
    92,
    93,
    118,
    89,
    63,
    60,
    95,
    75,
    82,
    69,
    67,
    68,
    78,
    103,
    36
  ],
  [
    39,
    9,
    7,
    3,
    2,
    9,
    18,
    39,
    62,
    125,
    119,
    145,
    73,
    68,
    84,
    91,
    66,
    74,
    56,
    68,
    59,
    64,
    42,
    63
  ],
  [
    27,
    10,
    4,
    13,
    4,
    7,
    14,
    32,
    41,
    50,
    93,
    111,
    126,
    58,
    62,
    70,
    55,
    36,
    39,
    54,
    50,
    83,
    67,
    53
  ],
  [
    23,
    12,
    13,
    3,
    9,
    7,
    25,
    42,
    76,
    120,
    114,
    136,
    134,
    81,
    111,
    94,
    86,
    71,
    56,
    50,
    58,
    74,
    71,
    39
  ],
  [
    26,
    12,
    6,
    5,
    3,
    4,
    17,
    40,
    53,
    102,
    133,
    99,
    86,
    66,
    72,
    61,
    79,
    81,
    67,
    69,
    49,
    43,
    48,
    46
  ],
  [
    32,
    13,
    6,
    5,
    5,
    3,
    19,
    37,
    35,
    76,
    64,
    45,
    36,
    31,
    68,
    42,
    56,
    35,
    41,
    60,
    62,
    55,
    92,
    46
  ]
];
  const Q5_BY_DAY           = [
  {
    "day": "T2",
    "en": "Mon",
    "count": 1174
  },
  {
    "day": "T3",
    "en": "Tue",
    "count": 1384
  },
  {
    "day": "T4",
    "en": "Wed",
    "count": 1385
  },
  {
    "day": "T5",
    "en": "Thu",
    "count": 1159
  },
  {
    "day": "T6",
    "en": "Fri",
    "count": 1505
  },
  {
    "day": "T7",
    "en": "Sat",
    "count": 1267
  },
  {
    "day": "CN",
    "en": "Sun",
    "count": 964
  }
];
  const Q6_BY_HOUR          = [
  {
    "hour": 0,
    "count": 203
  },
  {
    "hour": 1,
    "count": 74
  },
  {
    "hour": 2,
    "count": 53
  },
  {
    "hour": 3,
    "count": 50
  },
  {
    "hour": 4,
    "count": 33
  },
  {
    "hour": 5,
    "count": 44
  },
  {
    "hour": 6,
    "count": 123
  },
  {
    "hour": 7,
    "count": 290
  },
  {
    "hour": 8,
    "count": 399
  },
  {
    "hour": 9,
    "count": 632
  },
  {
    "hour": 10,
    "count": 714
  },
  {
    "hour": 11,
    "count": 755
  },
  {
    "hour": 12,
    "count": 626
  },
  {
    "hour": 13,
    "count": 415
  },
  {
    "hour": 14,
    "count": 516
  },
  {
    "hour": 15,
    "count": 532
  },
  {
    "hour": 16,
    "count": 498
  },
  {
    "hour": 17,
    "count": 425
  },
  {
    "hour": 18,
    "count": 375
  },
  {
    "hour": 19,
    "count": 414
  },
  {
    "hour": 20,
    "count": 432
  },
  {
    "hour": 21,
    "count": 475
  },
  {
    "hour": 22,
    "count": 453
  },
  {
    "hour": 23,
    "count": 307
  }
];
  const Q5_TOP_NEG          = [
  {
    "vn": "Vấn đề xác minh, khoá, rủi ro tài khoản Amazon",
    "count": 1413
  },
  {
    "vn": "Khó khăn và thách thức khi bán hàng trên Amazon",
    "count": 1323
  },
  {
    "vn": "Bán hàng và vận hành kinh doanh trên Amazon",
    "count": 816
  },
  {
    "vn": "Thuế và Chi phí Kinh doanh trên Amazon cho Seller Việt Nam",
    "count": 662
  },
  {
    "vn": "Vận hành tài khoản và thanh toán quốc tế cho seller",
    "count": 434
  },
  {
    "vn": "Dịch vụ vận chuyển và fulfillment",
    "count": 393
  }
];
  const Q5_EARLY_DIST       = [
  {
    "vn": "Vấn đề xác minh, khoá, rủi ro tài khoản Amazon",
    "count": 1413,
    "slot": 432
  },
  {
    "vn": "Khó khăn và thách thức khi bán hàng trên Amazon",
    "count": 1323,
    "slot": 428
  },
  {
    "vn": "Bán hàng và vận hành kinh doanh trên Amazon",
    "count": 816,
    "slot": 239
  },
  {
    "vn": "Thuế và Chi phí Kinh doanh trên Amazon cho Seller Việt Nam",
    "count": 662,
    "slot": 183
  },
  {
    "vn": "Vận hành tài khoản và thanh toán quốc tế cho seller",
    "count": 434,
    "slot": 148
  },
  {
    "vn": "Dịch vụ vận chuyển và fulfillment",
    "count": 393,
    "slot": 107
  }
];
  const Q5_PEAK_WINDOW      = {
  "startHour": 9,
  "endHour": 13,
  "hours": [
    9,
    10,
    11,
    12
  ],
  "windowSize": 4,
  "totalMentions": 2727,
  "hourlyCounts": [
    203,
    74,
    53,
    50,
    33,
    44,
    123,
    290,
    399,
    632,
    714,
    755,
    626,
    415,
    516,
    532,
    498,
    425,
    375,
    414,
    432,
    475,
    453,
    307
  ]
};
  const KPI                 = {
  "totalPosts": 46636,
  "relevantPosts": 40258,
  "negativeMentions": 8838,
  "positiveMentions": 5157,
  "activeGroups": 9,
  "analysedGroups": 9,
  "soaGroups": 2,
  "ecGroups": 7,
  "masterTopics": 9,
  "subTopics": 24
};
  const OVERVIEW            = {
  "communities": [
    {
      "id": "ec7",
      "name": "Cộng đồng ETSY Việt Nam",
      "short": "ETSY VN",
      "type": "EC",
      "count": 12102
    },
    {
      "id": "ec4",
      "name": "Chuyện Nhà Bán (Shopee/TikTok)",
      "short": "Chuyện Nhà Bán",
      "type": "EC",
      "count": 11518
    },
    {
      "id": "ec3",
      "name": "Cộng Đồng Dropshipping & Shopify VN",
      "short": "Dropship & Shopify",
      "type": "EC",
      "count": 4836
    },
    {
      "id": "ec5",
      "name": "Etsy To Go",
      "short": "Etsy To Go",
      "type": "EC",
      "count": 4780
    },
    {
      "id": "soa2",
      "name": "Cộng đồng Amazon Sellers VN",
      "short": "CĐ Amazon Sellers",
      "type": "SOA",
      "count": 4775
    },
    {
      "id": "ec1",
      "name": "Cộng Đồng MMO",
      "short": "MMO",
      "type": "EC",
      "count": 704
    },
    {
      "id": "soa1",
      "name": "Amazon Sellers Viet Nam",
      "short": "Amazon Sellers VN",
      "type": "SOA",
      "count": 693
    },
    {
      "id": "ec2",
      "name": "Cuồng Phong Hội (Crossborder CBEC)",
      "short": "Cuồng Phong Hội",
      "type": "EC",
      "count": 429
    },
    {
      "id": "ec6",
      "name": "Etsy E-Z Cộng Đồng Etsy Việt",
      "short": "Etsy E-Z",
      "type": "EC",
      "count": 421
    }
  ],
  "personas": [
    {
      "id": "p_seller_ot",
      "short": "Seller",
      "segment": "Others",
      "vn": "Seller (Others)",
      "count": 14906,
      "pct": 37.0
    },
    {
      "id": "p_prospect_ot",
      "short": "Prospect",
      "segment": "Others",
      "vn": "Prospect (Others)",
      "count": 9500,
      "pct": 23.6
    },
    {
      "id": "p_svc_cbec",
      "short": "Service Provider",
      "segment": "CBEC",
      "vn": "Service Provider (CBEC)",
      "count": 6647,
      "pct": 16.5
    },
    {
      "id": "p_seller_az",
      "short": "Seller",
      "segment": "Amazon",
      "vn": "Seller (Amazon)",
      "count": 6530,
      "pct": 16.2
    },
    {
      "id": "p_prospect_az",
      "short": "Prospect",
      "segment": "Amazon",
      "vn": "Prospect (Amazon)",
      "count": 1886,
      "pct": 4.7
    },
    {
      "id": "p_svc_az",
      "short": "Service Provider",
      "segment": "Amazon",
      "vn": "Service Provider (Amazon)",
      "count": 768,
      "pct": 1.9
    }
  ],
  "totalRelevant": 40258,
  "soaTotal": 5468,
  "ecTotal": 34790,
  "soaPct": 14,
  "ecPct": 86,
  "soaGroupCount": 2,
  "ecGroupCount": 7,
  "monthsCount": 5,
  "topCommunity": {
    "id": "ec7",
    "name": "Cộng đồng ETSY Việt Nam",
    "short": "ETSY VN",
    "type": "EC",
    "count": 12102
  },
  "topCommunityPct": 30.1,
  "topPersona": {
    "id": "p_seller_ot",
    "short": "Seller",
    "segment": "Others",
    "vn": "Seller (Others)",
    "count": 14906,
    "pct": 37.0
  },
  "secondPersona": {
    "id": "p_prospect_ot",
    "short": "Prospect",
    "segment": "Others",
    "vn": "Prospect (Others)",
    "count": 9500,
    "pct": 23.6
  }
};
  const DATE_RANGE          = {
  "start": "2025-12-24",
  "end": "2026-04-06",
  "monthsCount": 5
};
  return {
    SOA_GROUPS, EC_GROUPS, ALL_GROUPS,
    MASTER_TOPICS, Q1_MASTER, Q1_WEIGHTS, SUBTOPICS,
    PERSONAS, Q2_MATRIX, Q3_SELLER_PROSPECT, Q3_SUBS,
    MONTHS, Q4_TRENDS, WEEKS, Q4_EVENTS, Q4_WEEKLY,
    DAYS_VN, DAYS_EN, Q56_HEATMAP, Q5_BY_DAY, Q6_BY_HOUR,
    Q5_TOP_NEG, Q5_EARLY_DIST, Q5_PEAK_WINDOW, KPI,
    OVERVIEW, DATE_RANGE,
  };
})();

window.ChiComData2 = (() => {
  const Q7_TOPICS      = [
  {
    "vn": "Chia sẻ, học hỏi & trợ giúp",
    "name": "Chia sẻ, học hỏi & trợ giúp",
    "count": 441
  },
  {
    "vn": "Hợp tác, hỗ trợ & vận hành",
    "name": "Hợp tác, hỗ trợ & vận hành",
    "count": 274
  },
  {
    "vn": "Kinh nghiệm & chiến lược",
    "name": "Kinh nghiệm & chiến lược",
    "count": 269
  },
  {
    "vn": "Sự kiện, đào tạo & kết nối",
    "name": "Sự kiện, đào tạo & kết nối",
    "count": 235
  },
  {
    "vn": "Bán hàng & vận hành",
    "name": "Bán hàng & vận hành",
    "count": 232
  },
  {
    "vn": "Passive income & cơ hội",
    "name": "Passive income & cơ hội",
    "count": 3
  }
];
  const Q7_BENEFITS    = [
  {
    "vn": "Thành công & thu nhập",
    "name": "Thành công & thu nhập",
    "count": 1517
  },
  {
    "vn": "Passive income",
    "name": "Passive income",
    "count": 231
  },
  {
    "vn": "Dễ bắt đầu",
    "name": "Dễ bắt đầu",
    "count": 183
  },
  {
    "vn": "Cơ hội thị trường",
    "name": "Cơ hội thị trường",
    "count": 142
  },
  {
    "vn": "Hỗ trợ & đào tạo",
    "name": "Hỗ trợ & đào tạo",
    "count": 65
  }
];
  const Q7_SENTIMENT   = {
  "positive": 13,
  "neutral": 65,
  "negative": 22
};
  const Q8_TRIGGERS    = [
  {
    "vn": "Thua lỗ / chi phí cao",
    "name": "Thua lỗ / chi phí cao",
    "count": 165
  },
  {
    "vn": "Lừa đảo / rủi ro",
    "name": "Lừa đảo / rủi ro",
    "count": 151
  },
  {
    "vn": "Kiệt sức / mất động lực",
    "name": "Kiệt sức / mất động lực",
    "count": 144
  },
  {
    "vn": "Chính sách phức tạp",
    "name": "Chính sách phức tạp",
    "count": 83
  },
  {
    "vn": "Tài khoản bị khóa",
    "name": "Tài khoản bị khóa",
    "count": 73
  },
  {
    "vn": "Cạnh tranh khốc liệt",
    "name": "Cạnh tranh khốc liệt",
    "count": 26
  },
  {
    "vn": "Thiếu kinh nghiệm / kỹ năng",
    "name": "Thiếu kinh nghiệm / kỹ năng",
    "count": 4
  }
];
  const Q8_PERSONA     = [
  {
    "label": "Seller (Others)",
    "count": 5802,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "label": "Seller (Amazon)",
    "count": 2541,
    "color": "oklch(0.70 0.17 60)"
  },
  {
    "label": "Prospect (Others)",
    "count": 380,
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "label": "Prospect (Amazon)",
    "count": 81,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "label": "Service Provider (CBEC)",
    "count": 28,
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "label": "Service Provider (Amazon)",
    "count": 6,
    "color": "oklch(0.60 0.20 25)"
  }
];
  const Q8_TREND       = [
  249,
  2701,
  2373,
  3335,
  180
];
  const Q9_BARRIERS    = [
  {
    "vn": "Thuế & pháp lý",
    "name": "Thuế & pháp lý",
    "count": 795
  },
  {
    "vn": "Thiếu kiến thức",
    "name": "Thiếu kiến thức",
    "count": 317
  },
  {
    "vn": "Thanh toán quốc tế",
    "name": "Thanh toán quốc tế",
    "count": 247
  },
  {
    "vn": "Xác minh tài khoản",
    "name": "Xác minh tài khoản",
    "count": 217
  },
  {
    "vn": "Vốn ban đầu",
    "name": "Vốn ban đầu",
    "count": 77
  },
  {
    "vn": "Chọn sản phẩm",
    "name": "Chọn sản phẩm",
    "count": 35
  },
  {
    "vn": "Vận chuyển quốc tế",
    "name": "Vận chuyển quốc tế",
    "count": 19
  },
  {
    "vn": "Tiếng Anh / giao tiếp",
    "name": "Tiếng Anh / giao tiếp",
    "count": 11
  }
];
  const Q9_Q7_PERSONAS = [
  {
    "name": "Seller (Others)",
    "count": 1063,
    "color": "oklch(0.55 0.17 260)"
  },
  {
    "name": "Prospect (Others)",
    "count": 689,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "name": "Service Provider (CBEC)",
    "count": 614,
    "color": "oklch(0.68 0.17 60)"
  },
  {
    "name": "Seller (Amazon)",
    "count": 528,
    "color": "oklch(0.58 0.14 190)"
  },
  {
    "name": "Prospect (Amazon)",
    "count": 128,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "name": "Service Provider (Amazon)",
    "count": 54,
    "color": "oklch(0.55 0.17 290)"
  },
  {
    "name": "Service Provider (Others)",
    "count": 1,
    "color": "oklch(0.55 0.17 260)"
  }
];
  const Q9_Q8_PERSONAS = [
  {
    "name": "Seller (Others)",
    "count": 453,
    "color": "oklch(0.55 0.17 260)"
  },
  {
    "name": "Seller (Amazon)",
    "count": 113,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "name": "Prospect (Others)",
    "count": 27,
    "color": "oklch(0.68 0.17 60)"
  },
  {
    "name": "Prospect (Amazon)",
    "count": 12,
    "color": "oklch(0.58 0.14 190)"
  },
  {
    "name": "Service Provider (Amazon)",
    "count": 1,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "name": "Service Provider (CBEC)",
    "count": 1,
    "color": "oklch(0.55 0.17 290)"
  }
];
  const Q10_TOP        = [
  {
    "vn": "Thời trang",
    "name": "Thời trang",
    "count": 320,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "vn": "Điện tử & Gadget",
    "name": "Điện tử & Gadget",
    "count": 232,
    "color": "oklch(0.68 0.17 50)"
  },
  {
    "vn": "Gia dụng & Bếp",
    "name": "Gia dụng & Bếp",
    "count": 202,
    "color": "oklch(0.75 0.17 90)"
  },
  {
    "vn": "Làm đẹp & Sức khỏe",
    "name": "Làm đẹp & Sức khỏe",
    "count": 111,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "vn": "Thực phẩm",
    "name": "Thực phẩm",
    "count": 102,
    "color": "oklch(0.58 0.14 190)"
  },
  {
    "vn": "Đồ chơi & Trẻ em",
    "name": "Đồ chơi & Trẻ em",
    "count": 84,
    "color": "oklch(0.55 0.17 290)"
  },
  {
    "vn": "Thú cưng",
    "name": "Thú cưng",
    "count": 56,
    "color": "oklch(0.60 0.20 320)"
  },
  {
    "vn": "Thể thao & Ngoài trời",
    "name": "Thể thao & Ngoài trời",
    "count": 51,
    "color": "oklch(0.55 0.15 230)"
  },
  {
    "vn": "Vali & Túi xách",
    "name": "Vali & Túi xách",
    "count": 42,
    "color": "oklch(0.55 0.17 260)"
  },
  {
    "vn": "Nội thất",
    "name": "Nội thất",
    "count": 40,
    "color": "oklch(0.65 0.12 60)"
  }
];
  const Q10_WEEKS      = [
  "Dec 22",
  "Dec 29",
  "Jan 5",
  "Jan 12",
  "Jan 19",
  "Jan 26",
  "Feb 2",
  "Feb 9",
  "Feb 16",
  "Feb 23",
  "Mar 2",
  "Mar 9",
  "Mar 16",
  "Mar 23",
  "Mar 30",
  "Apr 6"
];
  const Q10_WEEKLY     = [
  {
    "name": "Thời trang",
    "color": "oklch(0.60 0.20 25)",
    "points": [
      1,
      9,
      16,
      16,
      9,
      12,
      21,
      17,
      13,
      18,
      41,
      64,
      38,
      32,
      13,
      0
    ]
  },
  {
    "name": "Điện tử & Gadget",
    "color": "oklch(0.68 0.17 50)",
    "points": [
      2,
      17,
      7,
      14,
      19,
      11,
      21,
      24,
      5,
      20,
      18,
      23,
      14,
      30,
      7,
      0
    ]
  },
  {
    "name": "Gia dụng & Bếp",
    "color": "oklch(0.75 0.17 90)",
    "points": [
      2,
      5,
      10,
      9,
      9,
      5,
      15,
      9,
      5,
      13,
      21,
      24,
      30,
      31,
      14,
      0
    ]
  },
  {
    "name": "Làm đẹp & Sức khỏe",
    "color": "oklch(0.62 0.15 155)",
    "points": [
      1,
      6,
      8,
      6,
      3,
      1,
      10,
      7,
      1,
      4,
      2,
      20,
      23,
      15,
      4,
      0
    ]
  },
  {
    "name": "Thực phẩm",
    "color": "oklch(0.58 0.14 190)",
    "points": [
      1,
      4,
      1,
      10,
      4,
      9,
      21,
      17,
      3,
      5,
      6,
      8,
      6,
      6,
      1,
      0
    ]
  },
  {
    "name": "Đồ chơi & Trẻ em",
    "color": "oklch(0.55 0.17 290)",
    "points": [
      0,
      2,
      9,
      5,
      4,
      2,
      3,
      5,
      0,
      6,
      12,
      8,
      14,
      6,
      8,
      0
    ]
  },
  {
    "name": "Thú cưng",
    "color": "oklch(0.60 0.20 320)",
    "points": [
      0,
      3,
      3,
      4,
      5,
      3,
      7,
      5,
      0,
      2,
      5,
      5,
      6,
      8,
      0,
      0
    ]
  }
];
  const Q11_TOOLS        = [
  {
    "name": "FBA",
    "vn": "FBA",
    "count": 161,
    "use": 161,
    "satisfied": 20,
    "issues": 13
  },
  {
    "name": "PPC/Ads",
    "vn": "PPC/Ads",
    "count": 126,
    "use": 126,
    "satisfied": 43,
    "issues": 19
  },
  {
    "name": "FBM",
    "vn": "FBM",
    "count": 104,
    "use": 104,
    "satisfied": 7,
    "issues": 12
  },
  {
    "name": "Quản lý tồn kho",
    "vn": "Quản lý tồn kho",
    "count": 102,
    "use": 102,
    "satisfied": 27,
    "issues": 17
  },
  {
    "name": "Amazon Support",
    "vn": "Amazon Support",
    "count": 92,
    "use": 92,
    "satisfied": 3,
    "issues": 57
  },
  {
    "name": "Helium 10",
    "vn": "Helium 10",
    "count": 33,
    "use": 33,
    "satisfied": 9,
    "issues": 0
  },
  {
    "name": "Seller Central",
    "vn": "Seller Central",
    "count": 17,
    "use": 17,
    "satisfied": 2,
    "issues": 4
  },
  {
    "name": "Brand Registry",
    "vn": "Brand Registry",
    "count": 16,
    "use": 16,
    "satisfied": 2,
    "issues": 4
  },
  {
    "name": "Jungle Scout",
    "vn": "Jungle Scout",
    "count": 5,
    "use": 5,
    "satisfied": 1,
    "issues": 0
  },
  {
    "name": "Amazon Vine",
    "vn": "Amazon Vine",
    "count": 3,
    "use": 3,
    "satisfied": 0,
    "issues": 0
  }
];
  const Q11_ISSUES       = [
  {
    "vn": "Lỗi hệ thống / Bug",
    "name": "Lỗi hệ thống / Bug",
    "count": 470
  },
  {
    "vn": "Phí & chi phí cao",
    "name": "Phí & chi phí cao",
    "count": 125
  },
  {
    "vn": "Tài khoản bị khóa / suspend",
    "name": "Tài khoản bị khóa / suspend",
    "count": 122
  },
  {
    "vn": "Khó dùng / phức tạp",
    "name": "Khó dùng / phức tạp",
    "count": 84
  },
  {
    "vn": "Cập nhật chậm / outdated",
    "name": "Cập nhật chậm / outdated",
    "count": 13
  },
  {
    "vn": "Hỗ trợ chậm / kém",
    "name": "Hỗ trợ chậm / kém",
    "count": 10
  },
  {
    "vn": "Thiếu tính năng",
    "name": "Thiếu tính năng",
    "count": 7
  },
  {
    "vn": "Dữ liệu sai / không chính xác",
    "name": "Dữ liệu sai / không chính xác",
    "count": 2
  }
];
  const Q11_SATISFACTION = [
  {
    "vn": "Giá hợp lý / đáng tiền",
    "name": "Giá hợp lý / đáng tiền",
    "count": 267
  },
  {
    "vn": "Hiệu quả rõ rệt",
    "name": "Hiệu quả rõ rệt",
    "count": 234
  },
  {
    "vn": "Dễ dùng / trực quan",
    "name": "Dễ dùng / trực quan",
    "count": 201
  },
  {
    "vn": "Tiết kiệm thời gian",
    "name": "Tiết kiệm thời gian",
    "count": 119
  },
  {
    "vn": "Dữ liệu chính xác",
    "name": "Dữ liệu chính xác",
    "count": 84
  },
  {
    "vn": "Cộng đồng & tài liệu tốt",
    "name": "Cộng đồng & tài liệu tốt",
    "count": 56
  },
  {
    "vn": "Hỗ trợ tận tình",
    "name": "Hỗ trợ tận tình",
    "count": 26
  },
  {
    "vn": "Nhiều tính năng / đầy đủ",
    "name": "Nhiều tính năng / đầy đủ",
    "count": 10
  }
];
  const Q12_SERVICES   = [
  {
    "name": "Kế toán / Thuế",
    "vn": "Kế toán / Thuế",
    "count": 2357,
    "mentions": 2357,
    "need": 142,
    "satisfaction": 20,
    "demand": 6
  },
  {
    "name": "Vận chuyển / Forwarder",
    "vn": "Vận chuyển / Forwarder",
    "count": 1124,
    "mentions": 1124,
    "need": 72,
    "satisfaction": 36,
    "demand": 6
  },
  {
    "name": "Phần mềm / Tool",
    "vn": "Phần mềm / Tool",
    "count": 356,
    "mentions": 356,
    "need": 24,
    "satisfaction": 79,
    "demand": 7
  },
  {
    "name": "Nguồn hàng / Sourcing",
    "vn": "Nguồn hàng / Sourcing",
    "count": 308,
    "mentions": 308,
    "need": 22,
    "satisfaction": 70,
    "demand": 7
  },
  {
    "name": "Pháp lý / Nhãn hiệu",
    "vn": "Pháp lý / Nhãn hiệu",
    "count": 190,
    "mentions": 190,
    "need": 13,
    "satisfaction": 39,
    "demand": 7
  },
  {
    "name": "Trợ lý ảo / VA",
    "vn": "Trợ lý ảo / VA",
    "count": 66,
    "mentions": 66,
    "need": 5,
    "satisfaction": 71,
    "demand": 8
  },
  {
    "name": "Chụp ảnh sản phẩm",
    "vn": "Chụp ảnh sản phẩm",
    "count": 27,
    "mentions": 27,
    "need": 0,
    "satisfaction": 100,
    "demand": 0
  },
  {
    "name": "Tối ưu Listing",
    "vn": "Tối ưu Listing",
    "count": 24,
    "mentions": 24,
    "need": 6,
    "satisfaction": 86,
    "demand": 25
  }
];
  const Q13_COURSES    = [
  {
    "name": "Đào tạo tổng quát",
    "vn": "Đào tạo tổng quát",
    "count": 94,
    "mentions": 94,
    "seeking": 7,
    "interest": 7,
    "positive": 42,
    "negative": 5
  },
  {
    "name": "Mentor / Coaching",
    "vn": "Mentor / Coaching",
    "count": 18,
    "mentions": 18,
    "seeking": 1,
    "interest": 6,
    "positive": 7,
    "negative": 1
  },
  {
    "name": "Khóa Amazon FBA",
    "vn": "Khóa Amazon FBA",
    "count": 3,
    "mentions": 3,
    "seeking": 0,
    "interest": 0,
    "positive": 2,
    "negative": 0
  }
];
  const Q14_GROWTH     = [
  {
    "name": "Xây dựng Team",
    "count": 492,
    "color": "oklch(0.55 0.17 290)",
    "seeking": 19,
    "positive": 159,
    "mixed": 271,
    "negative": 62
  },
  {
    "name": "Tự động hóa & Tool",
    "count": 442,
    "color": "oklch(0.75 0.17 60)",
    "seeking": 16,
    "positive": 173,
    "mixed": 234,
    "negative": 35
  },
  {
    "name": "Scale vận hành",
    "count": 378,
    "color": "oklch(0.55 0.17 260)",
    "seeking": 10,
    "positive": 258,
    "mixed": 112,
    "negative": 8
  },
  {
    "name": "Mở rộng thị trường",
    "count": 226,
    "color": "oklch(0.60 0.20 25)",
    "seeking": 19,
    "positive": 30,
    "mixed": 187,
    "negative": 9
  },
  {
    "name": "Marketing & Quảng cáo",
    "count": 96,
    "color": "oklch(0.62 0.15 155)",
    "seeking": 4,
    "positive": 45,
    "mixed": 47,
    "negative": 4
  },
  {
    "name": "Tăng doanh thu",
    "count": 14,
    "color": "oklch(0.62 0.15 200)",
    "seeking": 0,
    "positive": 6,
    "mixed": 6,
    "negative": 2
  }
];
  return {
    Q7_TOPICS, Q7_BENEFITS, Q7_SENTIMENT,
    Q8_TRIGGERS, Q8_PERSONA, Q8_TREND,
    Q9_BARRIERS, Q9_Q7_PERSONAS, Q9_Q8_PERSONAS,
    Q10_TOP, Q10_WEEKS, Q10_WEEKLY,
    Q11_TOOLS, Q11_ISSUES, Q11_SATISFACTION,
    Q12_SERVICES, Q13_COURSES, Q14_GROWTH,
  };
})();
