// Generated by build_data.py from all_groups_classified_annotated.csv — do not edit
// Run: python build_data.py  to regenerate

window.TOPIC_COLORS = [
  "oklch(0.62 0.15 260)",
  "oklch(0.62 0.15 25)",
  "oklch(0.62 0.15 155)",
  "oklch(0.62 0.15 60)",
  "oklch(0.62 0.15 320)",
  "oklch(0.62 0.15 200)",
  "oklch(0.62 0.15 90)",
  "oklch(0.62 0.15 290)",
  "oklch(0.62 0.15 0)"
];

window.ChiComData = (() => {
  const TC = window.TOPIC_COLORS;

  const SOA_GROUPS = [
  {
    "id": "soa1",
    "name": "Amazon Sellers Viet Nam",
    "short": "Amazon Sellers VN",
    "type": "SOA"
  },
  {
    "id": "soa2",
    "name": "Cộng đồng Amazon Sellers VN",
    "short": "CĐ Amazon Sellers",
    "type": "SOA"
  },
  {
    "id": "soa3",
    "name": "Cộng Đồng MMO",
    "short": "MMO",
    "type": "SOA"
  }
];
  const EC_GROUPS  = [
  {
    "id": "ec1",
    "name": "Cuồng Phong Hội (Crossborder CBEC)",
    "short": "Cuồng Phong Hội",
    "type": "EC"
  },
  {
    "id": "ec2",
    "name": "Cộng Đồng Dropshipping & Shopify VN",
    "short": "Dropship & Shopify",
    "type": "EC"
  },
  {
    "id": "ec3",
    "name": "Chuyện Nhà Bán (Shopee/TikTok)",
    "short": "Chuyện Nhà Bán",
    "type": "EC"
  }
];
  const ALL_GROUPS = [...SOA_GROUPS, ...EC_GROUPS];

  const MASTER_TOPICS = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance"
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges"
  }
];

  const Q1_WEIGHTS = {
  "mt1": {
    "soa1": 16.9,
    "soa2": 38.3,
    "soa3": 38.8,
    "ec1": 7.0,
    "ec2": 6.2,
    "ec3": 13.1
  },
  "mt2": {
    "soa1": 0.0,
    "soa2": 0.0,
    "soa3": 0.0,
    "ec1": 0.0,
    "ec2": 0.0,
    "ec3": 0.0
  },
  "mt3": {
    "soa1": 27.7,
    "soa2": 27.5,
    "soa3": 7.5,
    "ec1": 0.0,
    "ec2": 4.3,
    "ec3": 8.3
  },
  "mt4": {
    "soa1": 3.6,
    "soa2": 0.3,
    "soa3": 0.7,
    "ec1": 8.8,
    "ec2": 0.8,
    "ec3": 0.1
  },
  "mt5": {
    "soa1": 9.7,
    "soa2": 3.4,
    "soa3": 21.0,
    "ec1": 0.0,
    "ec2": 10.9,
    "ec3": 1.7
  },
  "mt6": {
    "soa1": 14.8,
    "soa2": 6.2,
    "soa3": 1.4,
    "ec1": 33.2,
    "ec2": 15.5,
    "ec3": 22.6
  },
  "mt7": {
    "soa1": 7.1,
    "soa2": 12.0,
    "soa3": 25.1,
    "ec1": 47.1,
    "ec2": 55.3,
    "ec3": 38.8
  },
  "mt8": {
    "soa1": 20.2,
    "soa2": 12.2,
    "soa3": 5.4,
    "ec1": 3.9,
    "ec2": 6.9,
    "ec3": 15.4
  },
  "mt9": {
    "soa1": 0.0,
    "soa2": 0.0,
    "soa3": 0.0,
    "ec1": 0.0,
    "ec2": 0.0,
    "ec3": 0.0
  }
};

  const Q1_MASTER = [
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border",
    "weight": 30.9,
    "color": "oklch(0.62 0.15 90)"
  },
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support",
    "weight": 20.1,
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance",
    "weight": 15.6,
    "color": "oklch(0.62 0.15 200)"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management",
    "weight": 12.5,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization",
    "weight": 10.7,
    "color": "oklch(0.62 0.15 290)"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment",
    "weight": 7.8,
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services",
    "weight": 2.4,
    "color": "oklch(0.62 0.15 60)"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud",
    "weight": 0.0,
    "color": "oklch(0.62 0.15 25)"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges",
    "weight": 0.0,
    "color": "oklch(0.62 0.15 0)"
  }
];

  const SUBTOPICS = {
  "mt1": [
    "Chia sẻ chiến lược Amazon",
    "Kinh nghiệm launch SP mới",
    "Hỗ trợ seller mới bắt đầu",
    "Networking seller VN"
  ],
  "mt2": [
    "Cảnh báo scam Amazon",
    "Lừa đảo PPC agency",
    "Rủi ro suspension",
    "Phishing & hijack"
  ],
  "mt3": [
    "Tạo & verify tài khoản",
    "Health score & metrics",
    "Tool quản lý listing",
    "Xử lý A-Z claim"
  ],
  "mt4": [
    "Brand registry",
    "Kế toán US",
    "Pháp lý LLC",
    "Trademark & IP"
  ],
  "mt5": [
    "FBA vs FBM",
    "Forwarder VN→US",
    "Cước vận chuyển",
    "Kho 3PL ở Mỹ"
  ],
  "mt6": [
    "Payoneer & tài khoản US",
    "Thẻ Visa virtual",
    "Quy đổi USD→VND",
    "Hoàn thuế VAT EU"
  ],
  "mt7": [
    "TMĐT xuyên biên giới",
    "Dropshipping CBEC",
    "Nguồn hàng TQ",
    "Thủ tục XNK"
  ],
  "mt8": [
    "PPC optimization",
    "SEO listing",
    "A/B test main image",
    "Tối ưu CVR"
  ],
  "mt9": [
    "Khóa học mentor",
    "Thử thách 30 ngày",
    "Bootcamp PPC",
    "Coaching 1-1"
  ]
};

  const PERSONAS = [
  {
    "id": "p_seller_az",
    "short": "Seller",
    "segment": "Amazon",
    "vn": "Seller (Amazon)"
  },
  {
    "id": "p_prospect_az",
    "short": "Prospect",
    "segment": "Amazon",
    "vn": "Prospect (Amazon)"
  },
  {
    "id": "p_svc_az",
    "short": "Service Provider",
    "segment": "Amazon",
    "vn": "Service Provider (Amazon)"
  },
  {
    "id": "p_svc_cbec",
    "short": "Service Provider",
    "segment": "CBEC",
    "vn": "Service Provider (CBEC)"
  },
  {
    "id": "p_prospect_ot",
    "short": "Prospect",
    "segment": "Others",
    "vn": "Prospect (Others)"
  },
  {
    "id": "p_seller_ot",
    "short": "Seller",
    "segment": "Others",
    "vn": "Seller (Others)"
  }
];

  const Q2_MATRIX = {
  "mt1": {
    "p_seller_az": 3427,
    "p_prospect_az": 778,
    "p_svc_az": 858,
    "p_svc_cbec": 48,
    "p_prospect_ot": 0,
    "p_seller_ot": 13
  },
  "mt2": {
    "p_seller_az": 0,
    "p_prospect_az": 0,
    "p_svc_az": 0,
    "p_svc_cbec": 0,
    "p_prospect_ot": 0,
    "p_seller_ot": 0
  },
  "mt3": {
    "p_seller_az": 5058,
    "p_prospect_az": 1122,
    "p_svc_az": 139,
    "p_svc_cbec": 1,
    "p_prospect_ot": 1,
    "p_seller_ot": 15
  },
  "mt4": {
    "p_seller_az": 0,
    "p_prospect_az": 13,
    "p_svc_az": 156,
    "p_svc_cbec": 11,
    "p_prospect_ot": 1,
    "p_seller_ot": 0
  },
  "mt5": {
    "p_seller_az": 228,
    "p_prospect_az": 132,
    "p_svc_az": 270,
    "p_svc_cbec": 2756,
    "p_prospect_ot": 264,
    "p_seller_ot": 26
  },
  "mt6": {
    "p_seller_az": 3275,
    "p_prospect_az": 1020,
    "p_svc_az": 12,
    "p_svc_cbec": 211,
    "p_prospect_ot": 2020,
    "p_seller_ot": 1332
  },
  "mt7": {
    "p_seller_az": 1628,
    "p_prospect_az": 831,
    "p_svc_az": 285,
    "p_svc_cbec": 2761,
    "p_prospect_ot": 3865,
    "p_seller_ot": 3796
  },
  "mt8": {
    "p_seller_az": 2830,
    "p_prospect_az": 1426,
    "p_svc_az": 127,
    "p_svc_cbec": 0,
    "p_prospect_ot": 8,
    "p_seller_ot": 0
  },
  "mt9": {
    "p_seller_az": 0,
    "p_prospect_az": 0,
    "p_svc_az": 0,
    "p_svc_cbec": 0,
    "p_prospect_ot": 0,
    "p_seller_ot": 0
  }
};

  const Q3_SELLER_PROSPECT = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support",
    "seller": 3440,
    "prospect": 778,
    "sellerPct": 15.9,
    "prospectPct": 6.8,
    "diff": 9.1
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud",
    "seller": 0,
    "prospect": 0,
    "sellerPct": 0.0,
    "prospectPct": 0.0,
    "diff": 0.0
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management",
    "seller": 5073,
    "prospect": 1123,
    "sellerPct": 23.5,
    "prospectPct": 9.8,
    "diff": 13.7
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services",
    "seller": 0,
    "prospect": 14,
    "sellerPct": 0.0,
    "prospectPct": 0.1,
    "diff": -0.1
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment",
    "seller": 254,
    "prospect": 396,
    "sellerPct": 1.2,
    "prospectPct": 3.4,
    "diff": -2.2
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance",
    "seller": 4607,
    "prospect": 3040,
    "sellerPct": 21.3,
    "prospectPct": 26.5,
    "diff": -5.2
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border",
    "seller": 5424,
    "prospect": 4696,
    "sellerPct": 25.1,
    "prospectPct": 40.9,
    "diff": -15.8
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization",
    "seller": 2830,
    "prospect": 1434,
    "sellerPct": 13.1,
    "prospectPct": 12.5,
    "diff": 0.6
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges",
    "seller": 0,
    "prospect": 0,
    "sellerPct": 0.0,
    "prospectPct": 0.0,
    "diff": 0.0
  }
];

  const Q3_SUBS = [
  {
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "seller": 8.1,
    "prospect": 8.8,
    "diff": -0.7
  },
  {
    "vn": "Kinh nghiệm & chiến lược bán hàng trên Amazon",
    "seller": 10.8,
    "prospect": 6.6,
    "diff": 4.2
  },
  {
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "seller": 12.9,
    "prospect": 7.3,
    "diff": 5.6
  },
  {
    "vn": "Thuế và chi phí kinh doanh trên Amazon",
    "seller": 6.8,
    "prospect": 4.3,
    "diff": 2.5
  },
  {
    "vn": "Khó khăn & thách thức khi bán hàng Amazon",
    "seller": 4.9,
    "prospect": 3.3,
    "diff": 1.6
  },
  {
    "vn": "Dịch vụ hỗ trợ & tối ưu tài khoản",
    "seller": 8.1,
    "prospect": 4.4,
    "diff": 3.7
  },
  {
    "vn": "Hợp tác, hỗ trợ & vận hành bán hàng",
    "seller": 10.0,
    "prospect": 5.9,
    "diff": 4.1
  },
  {
    "vn": "Vấn đề xác minh, khoá, rủi ro tài khoản",
    "seller": 11.2,
    "prospect": 10.2,
    "diff": 1.0
  },
  {
    "vn": "Sự kiện, đào tạo và kết nối cộng đồng",
    "seller": 5.4,
    "prospect": 8.1,
    "diff": -2.7
  },
  {
    "vn": "Kinh doanh xuất nhập khẩu & quốc tế",
    "seller": 4.5,
    "prospect": 4.5,
    "diff": 0.0
  },
  {
    "vn": "Dịch vụ vận chuyển và fulfillment",
    "seller": 8.0,
    "prospect": 1.5,
    "diff": 6.5
  },
  {
    "vn": "Chia sẻ, học hỏi và hợp tác kinh nghiệm",
    "seller": 14.1,
    "prospect": 4.8,
    "diff": 9.3
  },
  {
    "vn": "Hướng dẫn & hỗ trợ người mới bắt đầu",
    "seller": 9.4,
    "prospect": 5.9,
    "diff": 3.5
  },
  {
    "vn": "Kinh doanh Amazon FBA và FBM",
    "seller": 4.1,
    "prospect": 7.4,
    "diff": -3.3
  },
  {
    "vn": "Vấn đề & thủ tục thanh toán, mở OTP",
    "seller": 4.2,
    "prospect": 7.5,
    "diff": -3.3
  },
  {
    "vn": "Bán hàng và vận hành Amazon",
    "seller": 12.9,
    "prospect": 9.5,
    "diff": 3.4
  },
  {
    "vn": "Thanh toán Amazon qua Payoneer",
    "seller": 13.0,
    "prospect": 6.0,
    "diff": 7.0
  },
  {
    "vn": "Vấn đề thanh toán quốc tế",
    "seller": 7.7,
    "prospect": 3.0,
    "diff": 4.7
  },
  {
    "vn": "Ưu đãi Helium 10, tool seller Amazon",
    "seller": 3.0,
    "prospect": 2.1,
    "diff": 0.9
  }
];

  const MONTHS = [
  "2025-12",
  "2026-01",
  "2026-02",
  "2026-03",
  "2026-04"
];

  const Q4_TRENDS = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "points": [
      99,
      1990,
      1323,
      1667,
      45
    ],
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "points": [
      0,
      0,
      0,
      0,
      0
    ],
    "color": "oklch(0.62 0.15 25)"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "points": [
      183,
      1905,
      1586,
      2419,
      243
    ],
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "points": [
      4,
      68,
      70,
      33,
      6
    ],
    "color": "oklch(0.62 0.15 60)"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "points": [
      60,
      1178,
      643,
      1682,
      113
    ],
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "points": [
      236,
      1910,
      2298,
      3187,
      239
    ],
    "color": "oklch(0.62 0.15 200)"
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "points": [
      341,
      3378,
      3113,
      6000,
      334
    ],
    "color": "oklch(0.62 0.15 90)"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "points": [
      120,
      1182,
      1028,
      1946,
      115
    ],
    "color": "oklch(0.62 0.15 290)"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "points": [
      0,
      0,
      0,
      0,
      0
    ],
    "color": "oklch(0.62 0.15 0)"
  }
];

  const WEEKS = [
  "Dec 22",
  "Dec 29",
  "Jan 5",
  "Jan 12",
  "Jan 19",
  "Jan 26",
  "Feb 2",
  "Feb 9",
  "Feb 16",
  "Feb 23",
  "Mar 2",
  "Mar 9",
  "Mar 16",
  "Mar 23",
  "Mar 30",
  "Apr 6"
];

  const Q4_EVENTS = [
  {
    "week": 2,
    "label": "Prime Big Deal"
  },
  {
    "week": 6,
    "label": "Black Friday"
  },
  {
    "week": 7,
    "label": "Cyber Monday"
  },
  {
    "week": 10,
    "label": "Boxing Day"
  }
];

  const Q4_WEEKLY = [
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "color": "oklch(0.62 0.15 90)",
    "points": [
      24,
      628,
      1083,
      810,
      566,
      715,
      761,
      699,
      537,
      1119,
      1105,
      1693,
      1562,
      1302,
      542,
      20
    ]
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "color": "oklch(0.62 0.15 200)",
    "points": [
      6,
      416,
      508,
      416,
      324,
      529,
      675,
      579,
      300,
      752,
      695,
      865,
      672,
      794,
      330,
      9
    ]
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "color": "oklch(0.62 0.15 155)",
    "points": [
      2,
      425,
      547,
      418,
      329,
      382,
      437,
      351,
      356,
      444,
      385,
      551,
      633,
      715,
      347,
      14
    ]
  },
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "color": "oklch(0.62 0.15 260)",
    "points": [
      7,
      321,
      328,
      346,
      577,
      547,
      391,
      413,
      247,
      272,
      434,
      464,
      364,
      317,
      94,
      2
    ]
  }
];

  const DAYS_VN = [
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "CN"
];
  const DAYS_EN = [
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun"
];

  const Q56_HEATMAP = [
  [
    35,
    13,
    7,
    16,
    4,
    8,
    18,
    45,
    63,
    65,
    99,
    103,
    82,
    52,
    61,
    80,
    81,
    56,
    44,
    46,
    83,
    80,
    32,
    26
  ],
  [
    25,
    6,
    7,
    6,
    8,
    8,
    13,
    56,
    73,
    94,
    95,
    117,
    88,
    67,
    58,
    96,
    77,
    84,
    70,
    72,
    68,
    76,
    92,
    34
  ],
  [
    38,
    9,
    4,
    2,
    2,
    9,
    20,
    35,
    58,
    122,
    119,
    150,
    76,
    69,
    86,
    93,
    68,
    73,
    59,
    69,
    60,
    65,
    42,
    68
  ],
  [
    28,
    11,
    3,
    13,
    5,
    7,
    15,
    34,
    39,
    50,
    98,
    113,
    129,
    58,
    60,
    74,
    57,
    36,
    38,
    52,
    50,
    95,
    66,
    55
  ],
  [
    23,
    13,
    12,
    5,
    9,
    6,
    24,
    42,
    71,
    117,
    113,
    136,
    140,
    83,
    110,
    94,
    87,
    68,
    53,
    51,
    58,
    76,
    73,
    39
  ],
  [
    26,
    12,
    6,
    5,
    3,
    4,
    17,
    44,
    54,
    105,
    138,
    97,
    85,
    66,
    74,
    61,
    83,
    82,
    67,
    69,
    48,
    42,
    48,
    48
  ],
  [
    34,
    14,
    6,
    4,
    4,
    3,
    20,
    37,
    37,
    73,
    65,
    47,
    36,
    33,
    69,
    43,
    54,
    36,
    42,
    62,
    64,
    57,
    95,
    46
  ]
];

  const Q5_BY_DAY = [
  {
    "day": "T2",
    "en": "Mon",
    "count": 1199
  },
  {
    "day": "T3",
    "en": "Tue",
    "count": 1390
  },
  {
    "day": "T4",
    "en": "Wed",
    "count": 1396
  },
  {
    "day": "T5",
    "en": "Thu",
    "count": 1186
  },
  {
    "day": "T6",
    "en": "Fri",
    "count": 1503
  },
  {
    "day": "T7",
    "en": "Sat",
    "count": 1284
  },
  {
    "day": "CN",
    "en": "Sun",
    "count": 981
  }
];

  const Q6_BY_HOUR = [
  {
    "hour": 0,
    "count": 209
  },
  {
    "hour": 1,
    "count": 78
  },
  {
    "hour": 2,
    "count": 45
  },
  {
    "hour": 3,
    "count": 51
  },
  {
    "hour": 4,
    "count": 35
  },
  {
    "hour": 5,
    "count": 45
  },
  {
    "hour": 6,
    "count": 127
  },
  {
    "hour": 7,
    "count": 293
  },
  {
    "hour": 8,
    "count": 395
  },
  {
    "hour": 9,
    "count": 626
  },
  {
    "hour": 10,
    "count": 727
  },
  {
    "hour": 11,
    "count": 763
  },
  {
    "hour": 12,
    "count": 636
  },
  {
    "hour": 13,
    "count": 428
  },
  {
    "hour": 14,
    "count": 518
  },
  {
    "hour": 15,
    "count": 541
  },
  {
    "hour": 16,
    "count": 507
  },
  {
    "hour": 17,
    "count": 435
  },
  {
    "hour": 18,
    "count": 373
  },
  {
    "hour": 19,
    "count": 421
  },
  {
    "hour": 20,
    "count": 431
  },
  {
    "hour": 21,
    "count": 491
  },
  {
    "hour": 22,
    "count": 448
  },
  {
    "hour": 23,
    "count": 316
  }
];

  const Q5_TOP_NEG = [
  {
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "count": 3491
  },
  {
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "count": 1896
  },
  {
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "count": 1673
  },
  {
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "count": 1237
  },
  {
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "count": 567
  },
  {
    "vn": "Vận chuyển, logistics và fulfillment",
    "count": 49
  }
];

  const Q5_EARLY_DIST = [
  {
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "count": 3491,
    "slot": 1221
  },
  {
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "count": 1896,
    "slot": 663
  },
  {
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "count": 1673,
    "slot": 585
  },
  {
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "count": 1237,
    "slot": 432
  },
  {
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "count": 567,
    "slot": 198
  },
  {
    "vn": "Vận chuyển, logistics và fulfillment",
    "count": 49,
    "slot": 17
  }
];

  const KPI = {
  "totalPosts": 46631,
  "relevantPosts": 40770,
  "negativeMentions": 8939,
  "positiveMentions": 5474,
  "activeGroups": 9,
  "analysedGroups": 6,
  "masterTopics": 7,
  "subTopics": 142
};

  return {
    SOA_GROUPS, EC_GROUPS, ALL_GROUPS,
    MASTER_TOPICS, Q1_MASTER, Q1_WEIGHTS, SUBTOPICS,
    PERSONAS, Q2_MATRIX,
    Q3_SELLER_PROSPECT, Q3_SUBS,
    MONTHS, Q4_TRENDS, WEEKS, Q4_EVENTS, Q4_WEEKLY,
    DAYS_VN, DAYS_EN, Q56_HEATMAP, Q5_BY_DAY, Q6_BY_HOUR,
    Q5_TOP_NEG, Q5_EARLY_DIST,
    KPI,
  };
})();

window.ChiComData2 = (() => {
  const Q7_TOPICS    = [
  {
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "count": 13166
  },
  {
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "count": 7870
  },
  {
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "count": 6336
  },
  {
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "count": 5124
  },
  {
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "count": 4391
  },
  {
    "vn": "Vận chuyển, logistics và fulfillment",
    "count": 3676
  }
];
  const Q7_BENEFITS  = [
  {
    "vn": "Cơ hội thị trường",
    "en": "Market opportunity",
    "count": 180
  },
  {
    "vn": "Hỗ trợ & đào tạo",
    "en": "Training & support",
    "count": 210
  },
  {
    "vn": "Thành công",
    "en": "Success stories",
    "count": 125
  },
  {
    "vn": "Dễ bắt đầu",
    "en": "Easy to start",
    "count": 165
  },
  {
    "vn": "Passive income",
    "en": "Passive income",
    "count": 55
  }
];
  const Q7_SENTIMENT = {
  "positive": 13,
  "neutral": 65,
  "negative": 22
};

  const Q8_TRIGGERS = [
  {
    "vn": "Tài khoản bị khóa",
    "count": 210,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "vn": "Thua lỗ / chi phí cao",
    "count": 168,
    "color": "oklch(0.70 0.17 60)"
  },
  {
    "vn": "Chính sách phức tạp",
    "count": 95,
    "color": "oklch(0.70 0.17 60)"
  },
  {
    "vn": "Kiệt sức / mất động lực",
    "count": 72,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "vn": "Cạnh tranh khốc liệt",
    "count": 58,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "vn": "Lừa đảo / rủi ro tổ lừa",
    "count": 40,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "vn": "Khác",
    "count": 28,
    "color": "oklch(0.75 0.05 260)"
  }
];
  const Q8_PERSONA  = [
  {
    "label": "Seller (Amazon)",
    "count": 410,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "label": "Prospect (Amazon)",
    "count": 120,
    "color": "oklch(0.70 0.17 60)"
  },
  {
    "label": "Seller (Others)",
    "count": 45,
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "label": "Service Provider (Amazon)",
    "count": 30,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "label": "Prospect (Others)",
    "count": 18,
    "color": "oklch(0.62 0.15 320)"
  }
];
  const Q8_TREND    = [
  241,
  2745,
  2402,
  3364,
  187
];

  const Q9_BARRIERS = [
  {
    "vn": "Vốn ban đầu",
    "en": "Capital",
    "count": 240
  },
  {
    "vn": "Xác minh tài khoản",
    "en": "Account verification",
    "count": 205
  },
  {
    "vn": "Thiếu kiến thức",
    "en": "Knowledge gap",
    "count": 185
  },
  {
    "vn": "Tiếng Anh / giao tiếp",
    "en": "English barrier",
    "count": 140
  },
  {
    "vn": "Vận chuyển quốc tế",
    "en": "Int'l shipping",
    "count": 125
  },
  {
    "vn": "Thuế & pháp lý",
    "en": "Tax & legal",
    "count": 95
  },
  {
    "vn": "Chọn sản phẩm",
    "en": "Product selection",
    "count": 82
  },
  {
    "vn": "Thanh toán quốc tế",
    "en": "Payment",
    "count": 60
  }
];

  const Q10_TOP    = [
  {
    "name": "Health & Beauty",
    "count": 38,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "name": "Apparel",
    "count": 26,
    "color": "oklch(0.68 0.17 50)"
  },
  {
    "name": "Home",
    "count": 22,
    "color": "oklch(0.75 0.17 90)"
  },
  {
    "name": "Groceries",
    "count": 15,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "name": "Furniture",
    "count": 12,
    "color": "oklch(0.58 0.14 190)"
  },
  {
    "name": "Coffee",
    "count": 10,
    "color": "oklch(0.55 0.17 290)"
  },
  {
    "name": "Toys",
    "count": 9,
    "color": "oklch(0.60 0.20 320)"
  },
  {
    "name": "Major Appliances",
    "count": 7,
    "color": "oklch(0.55 0.15 230)"
  },
  {
    "name": "Luggage",
    "count": 5,
    "color": "oklch(0.55 0.17 260)"
  }
];
  const Q10_WEEKS  = [
  "W40",
  "W41",
  "W42",
  "W43",
  "W44",
  "W45",
  "W46",
  "W47",
  "W48",
  "W49",
  "W50",
  "W51",
  "W52",
  "W53",
  "W54",
  "W55"
];
  const Q10_WEEKLY = [
  {
    "name": "Health & Beauty",
    "color": "oklch(0.60 0.20 25)",
    "points": [
      9.6,
      11.7,
      12.72,
      12.22,
      10.24,
      7.33,
      4.36,
      2.23,
      1.62,
      2.72,
      5.18,
      8.23,
      10.95,
      12.53,
      12.57,
      11.17
    ]
  },
  {
    "name": "Apparel",
    "color": "oklch(0.68 0.17 50)",
    "points": [
      10.93,
      10.94,
      9.3,
      6.49,
      3.37,
      0.88,
      0.5,
      0.5,
      2.09,
      4.65,
      7.07,
      8.58,
      8.79,
      7.79,
      6.05,
      4.32
    ]
  },
  {
    "name": "Home",
    "color": "oklch(0.75 0.17 90)",
    "points": [
      9.1,
      6.81,
      4.02,
      1.64,
      0.5,
      0.5,
      1.81,
      3.76,
      5.58,
      6.6,
      6.51,
      5.43,
      3.88,
      2.54,
      2.03,
      2.64
    ]
  },
  {
    "name": "Groceries",
    "color": "oklch(0.62 0.15 155)",
    "points": [
      3.23,
      1.36,
      0.5,
      0.63,
      1.82,
      3.41,
      4.7,
      5.11,
      4.42,
      2.85,
      1.0,
      0.5,
      0.5,
      0.5,
      2.4,
      5.05
    ]
  },
  {
    "name": "Furniture",
    "color": "oklch(0.58 0.14 190)",
    "points": [
      0.5,
      1.15,
      2.68,
      4.37,
      5.52,
      5.56,
      4.34,
      2.16,
      0.5,
      0.5,
      0.5,
      0.5,
      0.5,
      3.47,
      6.32,
      8.1
    ]
  },
  {
    "name": "Coffee",
    "color": "oklch(0.55 0.17 290)",
    "points": [
      2.88,
      5.09,
      6.57,
      6.72,
      5.36,
      2.82,
      0.5,
      0.5,
      0.5,
      0.5,
      0.5,
      1.52,
      4.54,
      6.71,
      7.41,
      6.52
    ]
  },
  {
    "name": "Toys",
    "color": "oklch(0.60 0.20 320)",
    "points": [
      6.97,
      7.64,
      6.61,
      4.17,
      1.04,
      0.5,
      0.5,
      0.5,
      0.5,
      0.5,
      2.86,
      4.96,
      5.84,
      5.34,
      3.78,
      1.83
    ]
  }
];

  const Q11_TOOLS        = [
  {
    "name": "FBA",
    "use": 180,
    "satisfied": 1.2,
    "issues": 5
  },
  {
    "name": "Amazon Support",
    "use": 145,
    "satisfied": 0.5,
    "issues": 8
  },
  {
    "name": "PPC/Ads",
    "use": 130,
    "satisfied": 3.5,
    "issues": 5
  },
  {
    "name": "FBM",
    "use": 110,
    "satisfied": 1,
    "issues": 0.5
  },
  {
    "name": "Brand Registry",
    "use": 85,
    "satisfied": 0.5,
    "issues": 2
  },
  {
    "name": "Inventory Mgmt",
    "use": 55,
    "satisfied": 0.4,
    "issues": 0.3
  },
  {
    "name": "Lightning Deal",
    "use": 42,
    "satisfied": 0.3,
    "issues": 2
  },
  {
    "name": "Seller Central",
    "use": 38,
    "satisfied": 0.2,
    "issues": 0.5
  },
  {
    "name": "Amazon Vine",
    "use": 18,
    "satisfied": 0.1,
    "issues": 0
  },
  {
    "name": "Subscribe & Save",
    "use": 12,
    "satisfied": 0.1,
    "issues": 0
  }
];
  const Q11_ISSUES       = [
  {
    "name": "Claim A-to-Z",
    "count": 55
  },
  {
    "name": "Suspended account",
    "count": 42
  },
  {
    "name": "PPC inefficiency",
    "count": 38
  },
  {
    "name": "Listing errors",
    "count": 28
  },
  {
    "name": "Inventory issue",
    "count": 22
  },
  {
    "name": "FBA fee",
    "count": 18
  },
  {
    "name": "A9 ranking",
    "count": 14
  },
  {
    "name": "Bugs",
    "count": 10
  }
];
  const Q11_SATISFACTION = [
  {
    "name": "Ease of setup",
    "count": 42
  },
  {
    "name": "Reach & traffic",
    "count": 58
  },
  {
    "name": "Scale",
    "count": 18
  },
  {
    "name": "Tăng doanh số",
    "count": 12
  }
];

  const Q12_SERVICES = [
  {
    "name": "Accountant/Tax",
    "mentions": 177,
    "need": 35,
    "satisfaction": 80,
    "demand": 29
  },
  {
    "name": "Legal/Trademark",
    "mentions": 108,
    "need": 40,
    "satisfaction": 75,
    "demand": 32
  },
  {
    "name": "Listing Optimization",
    "mentions": 107,
    "need": 58,
    "satisfaction": 68,
    "demand": 42
  },
  {
    "name": "Product Sourcing",
    "mentions": 62,
    "need": 48,
    "satisfaction": 82,
    "demand": 52
  },
  {
    "name": "Software/Tools",
    "mentions": 55,
    "need": 32,
    "satisfaction": 85,
    "demand": 50
  },
  {
    "name": "Freight Forwarder",
    "mentions": 42,
    "need": 18,
    "satisfaction": 70,
    "demand": 40
  }
];
  const Q13_COURSES  = [
  {
    "name": "Mentorship/Coaching",
    "mentions": 45,
    "seeking": 32,
    "interest": 82,
    "positive": 38,
    "negative": 6
  },
  {
    "name": "General Training",
    "mentions": 22,
    "seeking": 15,
    "interest": 68,
    "positive": 18,
    "negative": 4
  },
  {
    "name": "Listing Optimization",
    "mentions": 14,
    "seeking": 8,
    "interest": 72,
    "positive": 11,
    "negative": 2
  },
  {
    "name": "Amazon Course",
    "mentions": 6,
    "seeking": 4,
    "interest": 70,
    "positive": 5,
    "negative": 1
  }
];
  const Q14_GROWTH   = [
  {
    "name": "Scaling Operations",
    "count": 180,
    "color": "oklch(0.55 0.17 260)",
    "seeking": 140,
    "positive": 20,
    "mixed": 15,
    "negative": 5
  },
  {
    "name": "Marketing & Ads",
    "count": 150,
    "color": "oklch(0.62 0.15 155)",
    "seeking": 115,
    "positive": 18,
    "mixed": 12,
    "negative": 5
  },
  {
    "name": "Automation & Tools",
    "count": 120,
    "color": "oklch(0.75 0.17 60)",
    "seeking": 90,
    "positive": 15,
    "mixed": 10,
    "negative": 5
  },
  {
    "name": "Revenue Growth",
    "count": 95,
    "color": "oklch(0.62 0.15 200)",
    "seeking": 70,
    "positive": 12,
    "mixed": 8,
    "negative": 5
  },
  {
    "name": "Team Building",
    "count": 72,
    "color": "oklch(0.55 0.17 290)",
    "seeking": 55,
    "positive": 10,
    "mixed": 5,
    "negative": 2
  },
  {
    "name": "Market Expansion",
    "count": 48,
    "color": "oklch(0.60 0.20 25)",
    "seeking": 38,
    "positive": 6,
    "mixed": 3,
    "negative": 1
  }
];

  return {
    Q7_TOPICS, Q7_BENEFITS, Q7_SENTIMENT,
    Q8_TRIGGERS, Q8_PERSONA, Q8_TREND,
    Q9_BARRIERS,
    Q10_TOP, Q10_WEEKS, Q10_WEEKLY,
    Q11_TOOLS, Q11_ISSUES, Q11_SATISFACTION,
    Q12_SERVICES, Q13_COURSES, Q14_GROWTH,
  };
})();
