// Auto-generated by ChiCom backend — do not edit
window.TOPIC_COLORS = [
  "oklch(0.62 0.15 260)",
  "oklch(0.62 0.15 25)",
  "oklch(0.62 0.15 155)",
  "oklch(0.62 0.15 60)",
  "oklch(0.62 0.15 320)",
  "oklch(0.62 0.15 200)",
  "oklch(0.62 0.15 90)",
  "oklch(0.62 0.15 290)",
  "oklch(0.62 0.15 0)"
];

window.ChiComData = (() => {
  const SOA_GROUPS = [
  {
    "id": "soa1",
    "name": "Amazon Sellers Viet Nam",
    "short": "Amazon Sellers VN",
    "type": "SOA"
  },
  {
    "id": "soa2",
    "name": "Cộng đồng Amazon Sellers VN",
    "short": "CĐ Amazon Sellers",
    "type": "SOA"
  },
  {
    "id": "soa3",
    "name": "Cộng Đồng MMO",
    "short": "MMO",
    "type": "SOA"
  }
];
  const EC_GROUPS  = [
  {
    "id": "ec1",
    "name": "Cuồng Phong Hội (Crossborder CBEC)",
    "short": "Cuồng Phong Hội",
    "type": "EC"
  },
  {
    "id": "ec2",
    "name": "Cộng Đồng Dropshipping & Shopify VN",
    "short": "Dropship & Shopify",
    "type": "EC"
  },
  {
    "id": "ec3",
    "name": "Chuyện Nhà Bán (Shopee/TikTok)",
    "short": "Chuyện Nhà Bán",
    "type": "EC"
  }
];
  const ALL_GROUPS = [...SOA_GROUPS, ...EC_GROUPS];
  const MASTER_TOPICS       = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance"
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges"
  }
];
  const Q1_WEIGHTS          = {
  "mt1": {
    "soa1": 16.9,
    "soa2": 38.3,
    "soa3": 38.8,
    "ec1": 7.0,
    "ec2": 6.2,
    "ec3": 13.1
  },
  "mt2": {
    "soa1": 0.0,
    "soa2": 0.0,
    "soa3": 0.0,
    "ec1": 0.0,
    "ec2": 0.0,
    "ec3": 0.0
  },
  "mt3": {
    "soa1": 27.7,
    "soa2": 27.5,
    "soa3": 7.5,
    "ec1": 0.0,
    "ec2": 4.3,
    "ec3": 8.3
  },
  "mt4": {
    "soa1": 3.6,
    "soa2": 0.3,
    "soa3": 0.7,
    "ec1": 8.8,
    "ec2": 0.8,
    "ec3": 0.1
  },
  "mt5": {
    "soa1": 9.7,
    "soa2": 3.4,
    "soa3": 21.0,
    "ec1": 0.0,
    "ec2": 10.9,
    "ec3": 1.7
  },
  "mt6": {
    "soa1": 14.8,
    "soa2": 6.2,
    "soa3": 1.4,
    "ec1": 33.2,
    "ec2": 15.5,
    "ec3": 22.6
  },
  "mt7": {
    "soa1": 7.1,
    "soa2": 12.0,
    "soa3": 25.1,
    "ec1": 47.1,
    "ec2": 55.3,
    "ec3": 38.8
  },
  "mt8": {
    "soa1": 20.2,
    "soa2": 12.2,
    "soa3": 5.4,
    "ec1": 3.9,
    "ec2": 6.9,
    "ec3": 15.4
  },
  "mt9": {
    "soa1": 0.0,
    "soa2": 0.0,
    "soa3": 0.0,
    "ec1": 0.0,
    "ec2": 0.0,
    "ec3": 0.0
  }
};
  const Q1_MASTER           = [
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border",
    "weight": 30.9,
    "color": "oklch(0.62 0.15 90)"
  },
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support",
    "weight": 20.1,
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance",
    "weight": 15.6,
    "color": "oklch(0.62 0.15 200)"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management",
    "weight": 12.5,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization",
    "weight": 10.7,
    "color": "oklch(0.62 0.15 290)"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment",
    "weight": 7.8,
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services",
    "weight": 2.4,
    "color": "oklch(0.62 0.15 60)"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud",
    "weight": 0.0,
    "color": "oklch(0.62 0.15 25)"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges",
    "weight": 0.0,
    "color": "oklch(0.62 0.15 0)"
  }
];
  const SUBTOPICS           = {
  "mt1": [
    "Chia sẻ chiến lược Amazon",
    "Kinh nghiệm launch SP mới",
    "Hỗ trợ seller mới bắt đầu",
    "Networking seller VN"
  ],
  "mt2": [
    "Cảnh báo scam Amazon",
    "Lừa đảo PPC agency",
    "Rủi ro suspension",
    "Phishing & hijack"
  ],
  "mt3": [
    "Tạo & verify tài khoản",
    "Health score & metrics",
    "Tool quản lý listing",
    "Xử lý A-Z claim"
  ],
  "mt4": [
    "Brand registry",
    "Kế toán US",
    "Pháp lý LLC",
    "Trademark & IP"
  ],
  "mt5": [
    "FBA vs FBM",
    "Forwarder VN→US",
    "Cước vận chuyển",
    "Kho 3PL ở Mỹ"
  ],
  "mt6": [
    "Payoneer & tài khoản US",
    "Thẻ Visa virtual",
    "Quy đổi USD→VND",
    "Hoàn thuế VAT EU"
  ],
  "mt7": [
    "TMĐT xuyên biên giới",
    "Dropshipping CBEC",
    "Nguồn hàng TQ",
    "Thủ tục XNK"
  ],
  "mt8": [
    "PPC optimization",
    "SEO listing",
    "A/B test main image",
    "Tối ưu CVR"
  ],
  "mt9": [
    "Khóa học mentor",
    "Thử thách 30 ngày",
    "Bootcamp PPC",
    "Coaching 1-1"
  ]
};
  const PERSONAS            = [
  {
    "id": "p_seller_az",
    "short": "Seller",
    "segment": "Amazon",
    "vn": "Seller (Amazon)"
  },
  {
    "id": "p_prospect_az",
    "short": "Prospect",
    "segment": "Amazon",
    "vn": "Prospect (Amazon)"
  },
  {
    "id": "p_svc_az",
    "short": "Service Provider",
    "segment": "Amazon",
    "vn": "Service Provider (Amazon)"
  },
  {
    "id": "p_svc_cbec",
    "short": "Service Provider",
    "segment": "CBEC",
    "vn": "Service Provider (CBEC)"
  },
  {
    "id": "p_prospect_ot",
    "short": "Prospect",
    "segment": "Others",
    "vn": "Prospect (Others)"
  },
  {
    "id": "p_seller_ot",
    "short": "Seller",
    "segment": "Others",
    "vn": "Seller (Others)"
  }
];
  const Q2_MATRIX           = {
  "mt1": {
    "p_seller_az": 3427,
    "p_prospect_az": 778,
    "p_svc_az": 858,
    "p_svc_cbec": 48,
    "p_prospect_ot": 0,
    "p_seller_ot": 13
  },
  "mt2": {
    "p_seller_az": 0,
    "p_prospect_az": 0,
    "p_svc_az": 0,
    "p_svc_cbec": 0,
    "p_prospect_ot": 0,
    "p_seller_ot": 0
  },
  "mt3": {
    "p_seller_az": 5058,
    "p_prospect_az": 1122,
    "p_svc_az": 139,
    "p_svc_cbec": 1,
    "p_prospect_ot": 1,
    "p_seller_ot": 15
  },
  "mt4": {
    "p_seller_az": 0,
    "p_prospect_az": 13,
    "p_svc_az": 156,
    "p_svc_cbec": 11,
    "p_prospect_ot": 1,
    "p_seller_ot": 0
  },
  "mt5": {
    "p_seller_az": 228,
    "p_prospect_az": 132,
    "p_svc_az": 270,
    "p_svc_cbec": 2756,
    "p_prospect_ot": 264,
    "p_seller_ot": 26
  },
  "mt6": {
    "p_seller_az": 3275,
    "p_prospect_az": 1020,
    "p_svc_az": 12,
    "p_svc_cbec": 211,
    "p_prospect_ot": 2020,
    "p_seller_ot": 1332
  },
  "mt7": {
    "p_seller_az": 1628,
    "p_prospect_az": 831,
    "p_svc_az": 285,
    "p_svc_cbec": 2761,
    "p_prospect_ot": 3865,
    "p_seller_ot": 3796
  },
  "mt8": {
    "p_seller_az": 2830,
    "p_prospect_az": 1426,
    "p_svc_az": 127,
    "p_svc_cbec": 0,
    "p_prospect_ot": 8,
    "p_seller_ot": 0
  },
  "mt9": {
    "p_seller_az": 0,
    "p_prospect_az": 0,
    "p_svc_az": 0,
    "p_svc_cbec": 0,
    "p_prospect_ot": 0,
    "p_seller_ot": 0
  }
};
  const Q3_SELLER_PROSPECT  = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "en": "Strategy, experience & community support",
    "seller": 3440,
    "prospect": 778,
    "sellerPct": 15.9,
    "prospectPct": 6.8,
    "diff": 9.1
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "en": "Risk warnings & fraud",
    "seller": 0,
    "prospect": 0,
    "sellerPct": 0.0,
    "prospectPct": 0.0,
    "diff": 0.0
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "en": "Account operations & management",
    "seller": 5073,
    "prospect": 1123,
    "sellerPct": 23.5,
    "prospectPct": 9.8,
    "diff": 13.7
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "en": "Legal, branding & services",
    "seller": 0,
    "prospect": 14,
    "sellerPct": 0.0,
    "prospectPct": 0.1,
    "diff": -0.1
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "en": "Shipping, logistics & fulfillment",
    "seller": 254,
    "prospect": 396,
    "sellerPct": 1.2,
    "prospectPct": 3.4,
    "diff": -2.2
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "en": "Payment, accounts & int'l finance",
    "seller": 4607,
    "prospect": 3040,
    "sellerPct": 21.3,
    "prospectPct": 26.5,
    "diff": -5.2
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "en": "Import-export & cross-border",
    "seller": 5424,
    "prospect": 4696,
    "sellerPct": 25.1,
    "prospectPct": 40.9,
    "diff": -15.8
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "en": "Business, ops & Amazon optimization",
    "seller": 2830,
    "prospect": 1434,
    "sellerPct": 13.1,
    "prospectPct": 12.5,
    "diff": 0.6
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "en": "Courses & Amazon challenges",
    "seller": 0,
    "prospect": 0,
    "sellerPct": 0.0,
    "prospectPct": 0.0,
    "diff": 0.0
  }
];
  const Q3_SUBS             = [
  {
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "seller": 1.29,
    "prospect": 1.29,
    "diff": 0.0
  },
  {
    "vn": "Kinh nghiệm & chiến lược bán hàng trên Amazon",
    "seller": 1.43,
    "prospect": 2.16,
    "diff": -0.73
  },
  {
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "seller": 0.48,
    "prospect": 0.29,
    "diff": 0.19
  },
  {
    "vn": "Thuế và chi phí kinh doanh trên Amazon",
    "seller": 6.84,
    "prospect": 7.04,
    "diff": -0.2
  },
  {
    "vn": "Khó khăn & thách thức khi bán hàng Amazon",
    "seller": 1.91,
    "prospect": 1.1,
    "diff": 0.81
  },
  {
    "vn": "Dịch vụ hỗ trợ & tối ưu tài khoản",
    "seller": 0.04,
    "prospect": 0.01,
    "diff": 0.03
  },
  {
    "vn": "Hợp tác, hỗ trợ & vận hành bán hàng",
    "seller": 1.0,
    "prospect": 1.3,
    "diff": -0.3
  },
  {
    "vn": "Vấn đề xác minh, khoá, rủi ro tài khoản",
    "seller": 1.55,
    "prospect": 1.44,
    "diff": 0.11
  },
  {
    "vn": "Sự kiện, đào tạo và kết nối cộng đồng",
    "seller": 0.33,
    "prospect": 0.54,
    "diff": -0.21
  },
  {
    "vn": "Kinh doanh xuất nhập khẩu & quốc tế",
    "seller": 0.22,
    "prospect": 0.57,
    "diff": -0.35
  },
  {
    "vn": "Dịch vụ vận chuyển và fulfillment",
    "seller": 1.65,
    "prospect": 2.83,
    "diff": -1.18
  },
  {
    "vn": "Chia sẻ, học hỏi và hợp tác kinh nghiệm",
    "seller": 1.71,
    "prospect": 1.84,
    "diff": -0.13
  },
  {
    "vn": "Hướng dẫn & hỗ trợ người mới bắt đầu",
    "seller": 1.42,
    "prospect": 3.32,
    "diff": -1.9
  },
  {
    "vn": "Kinh doanh Amazon FBA và FBM",
    "seller": 0.42,
    "prospect": 0.31,
    "diff": 0.11
  },
  {
    "vn": "Vấn đề & thủ tục thanh toán, mở OTP",
    "seller": 0.12,
    "prospect": 0.05,
    "diff": 0.07
  },
  {
    "vn": "Bán hàng và vận hành Amazon",
    "seller": 1.21,
    "prospect": 0.57,
    "diff": 0.64
  },
  {
    "vn": "Thanh toán Amazon qua Payoneer",
    "seller": 0.06,
    "prospect": 0.17,
    "diff": -0.11
  },
  {
    "vn": "Vấn đề thanh toán quốc tế",
    "seller": 0.46,
    "prospect": 0.84,
    "diff": -0.38
  },
  {
    "vn": "Ưu đãi Helium 10, tool seller Amazon",
    "seller": 0.03,
    "prospect": 0.01,
    "diff": 0.02
  }
];
  const MONTHS              = [
  "2025-12",
  "2026-01",
  "2026-02",
  "2026-03",
  "2026-04"
];
  const Q4_TRENDS           = [
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "points": [
      99,
      1990,
      1323,
      1667,
      45
    ],
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "id": "mt2",
    "vn": "Cảnh báo rủi ro & lừa đảo khi kinh doanh Amazon",
    "points": [
      0,
      0,
      0,
      0,
      0
    ],
    "color": "oklch(0.62 0.15 25)"
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "points": [
      183,
      1905,
      1586,
      2419,
      243
    ],
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "id": "mt4",
    "vn": "Dịch vụ & giải pháp pháp lý, thương hiệu",
    "points": [
      4,
      68,
      70,
      33,
      6
    ],
    "color": "oklch(0.62 0.15 60)"
  },
  {
    "id": "mt5",
    "vn": "Vận chuyển, logistics và fulfillment",
    "points": [
      60,
      1178,
      643,
      1682,
      113
    ],
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "points": [
      236,
      1910,
      2298,
      3187,
      239
    ],
    "color": "oklch(0.62 0.15 200)"
  },
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "points": [
      341,
      3378,
      3113,
      6000,
      334
    ],
    "color": "oklch(0.62 0.15 90)"
  },
  {
    "id": "mt8",
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "points": [
      120,
      1182,
      1028,
      1946,
      115
    ],
    "color": "oklch(0.62 0.15 290)"
  },
  {
    "id": "mt9",
    "vn": "Khóa học và thách thức kinh doanh Amazon",
    "points": [
      0,
      0,
      0,
      0,
      0
    ],
    "color": "oklch(0.62 0.15 0)"
  }
];
  const WEEKS               = [
  "Dec 22",
  "Dec 29",
  "Jan 5",
  "Jan 12",
  "Jan 19",
  "Jan 26",
  "Feb 2",
  "Feb 9",
  "Feb 16",
  "Feb 23",
  "Mar 2",
  "Mar 9",
  "Mar 16",
  "Mar 23",
  "Mar 30",
  "Apr 6"
];
  const Q4_EVENTS           = [
  {
    "week": 11,
    "label": "Spike Mar 9 · +69%"
  },
  {
    "week": 12,
    "label": "Spike Mar 16 · +70%"
  },
  {
    "week": 13,
    "label": "Spike Mar 23 · +56%"
  }
];
  const Q4_WEEKLY           = [
  {
    "id": "mt7",
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "color": "oklch(0.62 0.15 90)",
    "points": [
      24,
      628,
      1083,
      810,
      566,
      715,
      761,
      699,
      537,
      1119,
      1105,
      1693,
      1562,
      1302,
      542,
      20
    ]
  },
  {
    "id": "mt6",
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "color": "oklch(0.62 0.15 200)",
    "points": [
      6,
      416,
      508,
      416,
      324,
      529,
      675,
      579,
      300,
      752,
      695,
      865,
      672,
      794,
      330,
      9
    ]
  },
  {
    "id": "mt3",
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "color": "oklch(0.62 0.15 155)",
    "points": [
      2,
      425,
      547,
      418,
      329,
      382,
      437,
      351,
      356,
      444,
      385,
      551,
      633,
      715,
      347,
      14
    ]
  },
  {
    "id": "mt1",
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "color": "oklch(0.62 0.15 260)",
    "points": [
      7,
      321,
      328,
      346,
      577,
      547,
      391,
      413,
      247,
      272,
      434,
      464,
      364,
      317,
      94,
      2
    ]
  }
];
  const DAYS_VN             = [
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "CN"
];
  const DAYS_EN             = [
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun"
];
  const Q56_HEATMAP         = [
  [
    35,
    13,
    7,
    16,
    4,
    8,
    18,
    45,
    63,
    65,
    99,
    103,
    82,
    52,
    61,
    80,
    81,
    56,
    44,
    46,
    83,
    80,
    32,
    26
  ],
  [
    25,
    6,
    7,
    6,
    8,
    8,
    13,
    56,
    73,
    94,
    95,
    117,
    88,
    67,
    58,
    96,
    77,
    84,
    70,
    72,
    68,
    76,
    92,
    34
  ],
  [
    38,
    9,
    4,
    2,
    2,
    9,
    20,
    35,
    58,
    122,
    119,
    150,
    76,
    69,
    86,
    93,
    68,
    73,
    59,
    69,
    60,
    65,
    42,
    68
  ],
  [
    28,
    11,
    3,
    13,
    5,
    7,
    15,
    34,
    39,
    50,
    98,
    113,
    129,
    58,
    60,
    74,
    57,
    36,
    38,
    52,
    50,
    95,
    66,
    55
  ],
  [
    23,
    13,
    12,
    5,
    9,
    6,
    24,
    42,
    71,
    117,
    113,
    136,
    140,
    83,
    110,
    94,
    87,
    68,
    53,
    51,
    58,
    76,
    73,
    39
  ],
  [
    26,
    12,
    6,
    5,
    3,
    4,
    17,
    44,
    54,
    105,
    138,
    97,
    85,
    66,
    74,
    61,
    83,
    82,
    67,
    69,
    48,
    42,
    48,
    48
  ],
  [
    34,
    14,
    6,
    4,
    4,
    3,
    20,
    37,
    37,
    73,
    65,
    47,
    36,
    33,
    69,
    43,
    54,
    36,
    42,
    62,
    64,
    57,
    95,
    46
  ]
];
  const Q5_BY_DAY           = [
  {
    "day": "T2",
    "en": "Mon",
    "count": 1199
  },
  {
    "day": "T3",
    "en": "Tue",
    "count": 1390
  },
  {
    "day": "T4",
    "en": "Wed",
    "count": 1396
  },
  {
    "day": "T5",
    "en": "Thu",
    "count": 1186
  },
  {
    "day": "T6",
    "en": "Fri",
    "count": 1503
  },
  {
    "day": "T7",
    "en": "Sat",
    "count": 1284
  },
  {
    "day": "CN",
    "en": "Sun",
    "count": 981
  }
];
  const Q6_BY_HOUR          = [
  {
    "hour": 0,
    "count": 209
  },
  {
    "hour": 1,
    "count": 78
  },
  {
    "hour": 2,
    "count": 45
  },
  {
    "hour": 3,
    "count": 51
  },
  {
    "hour": 4,
    "count": 35
  },
  {
    "hour": 5,
    "count": 45
  },
  {
    "hour": 6,
    "count": 127
  },
  {
    "hour": 7,
    "count": 293
  },
  {
    "hour": 8,
    "count": 395
  },
  {
    "hour": 9,
    "count": 626
  },
  {
    "hour": 10,
    "count": 727
  },
  {
    "hour": 11,
    "count": 763
  },
  {
    "hour": 12,
    "count": 636
  },
  {
    "hour": 13,
    "count": 428
  },
  {
    "hour": 14,
    "count": 518
  },
  {
    "hour": 15,
    "count": 541
  },
  {
    "hour": 16,
    "count": 507
  },
  {
    "hour": 17,
    "count": 435
  },
  {
    "hour": 18,
    "count": 373
  },
  {
    "hour": 19,
    "count": 421
  },
  {
    "hour": 20,
    "count": 431
  },
  {
    "hour": 21,
    "count": 491
  },
  {
    "hour": 22,
    "count": 448
  },
  {
    "hour": 23,
    "count": 316
  }
];
  const Q5_TOP_NEG          = [
  {
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "count": 3491
  },
  {
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "count": 1896
  },
  {
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "count": 1673
  },
  {
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "count": 1237
  },
  {
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "count": 567
  },
  {
    "vn": "Vận chuyển, logistics và fulfillment",
    "count": 49
  }
];
  const Q5_EARLY_DIST       = [
  {
    "vn": "Vận hành và quản lý tài khoản Amazon Seller",
    "count": 3491,
    "slot": 178
  },
  {
    "vn": "Kinh doanh xuất nhập khẩu & TMĐT xuyên biên giới",
    "count": 1896,
    "slot": 97
  },
  {
    "vn": "Thanh toán, tài khoản và tài chính quốc tế",
    "count": 1673,
    "slot": 82
  },
  {
    "vn": "Chiến lược, kinh nghiệm & hỗ trợ cộng đồng bán hàng",
    "count": 1237,
    "slot": 66
  },
  {
    "vn": "Kinh doanh, vận hành và tối ưu hóa bán hàng Amazon",
    "count": 567,
    "slot": 36
  },
  {
    "vn": "Vận chuyển, logistics và fulfillment",
    "count": 49,
    "slot": 4
  }
];
  const KPI                 = {
  "totalPosts": 46631,
  "relevantPosts": 40770,
  "negativeMentions": 8939,
  "positiveMentions": 5474,
  "activeGroups": 9,
  "analysedGroups": 6,
  "masterTopics": 7,
  "subTopics": 142
};
  return {
    SOA_GROUPS, EC_GROUPS, ALL_GROUPS,
    MASTER_TOPICS, Q1_MASTER, Q1_WEIGHTS, SUBTOPICS,
    PERSONAS, Q2_MATRIX, Q3_SELLER_PROSPECT, Q3_SUBS,
    MONTHS, Q4_TRENDS, WEEKS, Q4_EVENTS, Q4_WEEKLY,
    DAYS_VN, DAYS_EN, Q56_HEATMAP, Q5_BY_DAY, Q6_BY_HOUR,
    Q5_TOP_NEG, Q5_EARLY_DIST, KPI,
  };
})();

window.ChiComData2 = (() => {
  const Q7_TOPICS      = [
  {
    "vn": "Chia sẻ, học hỏi & trợ giúp",
    "name": "Chia sẻ, học hỏi & trợ giúp",
    "count": 441
  },
  {
    "vn": "Hợp tác, hỗ trợ & vận hành",
    "name": "Hợp tác, hỗ trợ & vận hành",
    "count": 274
  },
  {
    "vn": "Kinh nghiệm & chiến lược",
    "name": "Kinh nghiệm & chiến lược",
    "count": 269
  },
  {
    "vn": "Sự kiện, đào tạo & kết nối",
    "name": "Sự kiện, đào tạo & kết nối",
    "count": 235
  },
  {
    "vn": "Bán hàng & vận hành",
    "name": "Bán hàng & vận hành",
    "count": 232
  },
  {
    "vn": "Passive income & cơ hội",
    "name": "Passive income & cơ hội",
    "count": 3
  }
];
  const Q7_BENEFITS    = [
  {
    "vn": "Thành công & thu nhập",
    "name": "Thành công & thu nhập",
    "count": 1517
  },
  {
    "vn": "Passive income",
    "name": "Passive income",
    "count": 231
  },
  {
    "vn": "Dễ bắt đầu",
    "name": "Dễ bắt đầu",
    "count": 183
  },
  {
    "vn": "Cơ hội thị trường",
    "name": "Cơ hội thị trường",
    "count": 142
  },
  {
    "vn": "Hỗ trợ & đào tạo",
    "name": "Hỗ trợ & đào tạo",
    "count": 65
  }
];
  const Q7_SENTIMENT   = {
  "positive": 13,
  "neutral": 65,
  "negative": 22
};
  const Q8_TRIGGERS    = [
  {
    "vn": "Thua lỗ / chi phí cao",
    "name": "Thua lỗ / chi phí cao",
    "count": 158
  },
  {
    "vn": "Lừa đảo / rủi ro",
    "name": "Lừa đảo / rủi ro",
    "count": 141
  },
  {
    "vn": "Kiệt sức / mất động lực",
    "name": "Kiệt sức / mất động lực",
    "count": 139
  },
  {
    "vn": "Chính sách phức tạp",
    "name": "Chính sách phức tạp",
    "count": 78
  },
  {
    "vn": "Tài khoản bị khóa",
    "name": "Tài khoản bị khóa",
    "count": 70
  },
  {
    "vn": "Cạnh tranh khốc liệt",
    "name": "Cạnh tranh khốc liệt",
    "count": 26
  },
  {
    "vn": "Thiếu kinh nghiệm / kỹ năng",
    "name": "Thiếu kinh nghiệm / kỹ năng",
    "count": 4
  }
];
  const Q8_PERSONA     = [
  {
    "label": "Seller (Amazon)",
    "count": 6616,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "label": "Seller (Others)",
    "count": 1962,
    "color": "oklch(0.70 0.17 60)"
  },
  {
    "label": "Prospect (Amazon)",
    "count": 272,
    "color": "oklch(0.62 0.15 260)"
  },
  {
    "label": "Prospect (Others)",
    "count": 76,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "label": "Service Provider (CBEC)",
    "count": 7,
    "color": "oklch(0.62 0.15 320)"
  },
  {
    "label": "Service Provider (Amazon)",
    "count": 6,
    "color": "oklch(0.60 0.20 25)"
  }
];
  const Q8_TREND       = [
  241,
  2745,
  2402,
  3364,
  187
];
  const Q9_BARRIERS    = [
  {
    "vn": "Thuế & pháp lý",
    "name": "Thuế & pháp lý",
    "count": 830
  },
  {
    "vn": "Thiếu kiến thức",
    "name": "Thiếu kiến thức",
    "count": 320
  },
  {
    "vn": "Thanh toán quốc tế",
    "name": "Thanh toán quốc tế",
    "count": 256
  },
  {
    "vn": "Xác minh tài khoản",
    "name": "Xác minh tài khoản",
    "count": 210
  },
  {
    "vn": "Vốn ban đầu",
    "name": "Vốn ban đầu",
    "count": 70
  },
  {
    "vn": "Chọn sản phẩm",
    "name": "Chọn sản phẩm",
    "count": 37
  },
  {
    "vn": "Vận chuyển quốc tế",
    "name": "Vận chuyển quốc tế",
    "count": 19
  },
  {
    "vn": "Tiếng Anh / giao tiếp",
    "name": "Tiếng Anh / giao tiếp",
    "count": 13
  }
];
  const Q10_TOP        = [
  {
    "vn": "Apparel",
    "name": "Apparel",
    "count": 320,
    "color": "oklch(0.60 0.20 25)"
  },
  {
    "vn": "Electronics & Gadgets",
    "name": "Electronics & Gadgets",
    "count": 232,
    "color": "oklch(0.68 0.17 50)"
  },
  {
    "vn": "Home & Kitchen",
    "name": "Home & Kitchen",
    "count": 202,
    "color": "oklch(0.75 0.17 90)"
  },
  {
    "vn": "Health & Beauty",
    "name": "Health & Beauty",
    "count": 111,
    "color": "oklch(0.62 0.15 155)"
  },
  {
    "vn": "Grocery & Food",
    "name": "Grocery & Food",
    "count": 102,
    "color": "oklch(0.58 0.14 190)"
  },
  {
    "vn": "Toys & Kids",
    "name": "Toys & Kids",
    "count": 84,
    "color": "oklch(0.55 0.17 290)"
  },
  {
    "vn": "Pet Supplies",
    "name": "Pet Supplies",
    "count": 56,
    "color": "oklch(0.60 0.20 320)"
  },
  {
    "vn": "Sports & Outdoors",
    "name": "Sports & Outdoors",
    "count": 51,
    "color": "oklch(0.55 0.15 230)"
  },
  {
    "vn": "Luggage & Bags",
    "name": "Luggage & Bags",
    "count": 42,
    "color": "oklch(0.55 0.17 260)"
  },
  {
    "vn": "Furniture",
    "name": "Furniture",
    "count": 40,
    "color": "oklch(0.65 0.12 60)"
  }
];
  const Q10_WEEKS      = [
  "Dec 22",
  "Dec 29",
  "Jan 5",
  "Jan 12",
  "Jan 19",
  "Jan 26",
  "Feb 2",
  "Feb 9",
  "Feb 16",
  "Feb 23",
  "Mar 2",
  "Mar 9",
  "Mar 16",
  "Mar 23",
  "Mar 30",
  "Apr 6"
];
  const Q10_WEEKLY     = [
  {
    "name": "Apparel",
    "color": "oklch(0.60 0.20 25)",
    "points": [
      1,
      9,
      16,
      16,
      9,
      12,
      21,
      17,
      13,
      18,
      41,
      64,
      38,
      32,
      13,
      0
    ]
  },
  {
    "name": "Electronics & Gadgets",
    "color": "oklch(0.68 0.17 50)",
    "points": [
      2,
      17,
      7,
      14,
      19,
      11,
      21,
      24,
      5,
      20,
      18,
      23,
      14,
      30,
      7,
      0
    ]
  },
  {
    "name": "Home & Kitchen",
    "color": "oklch(0.75 0.17 90)",
    "points": [
      2,
      5,
      10,
      9,
      9,
      5,
      15,
      9,
      5,
      13,
      21,
      24,
      30,
      31,
      14,
      0
    ]
  },
  {
    "name": "Health & Beauty",
    "color": "oklch(0.62 0.15 155)",
    "points": [
      1,
      6,
      8,
      6,
      3,
      1,
      10,
      7,
      1,
      4,
      2,
      20,
      23,
      15,
      4,
      0
    ]
  },
  {
    "name": "Grocery & Food",
    "color": "oklch(0.58 0.14 190)",
    "points": [
      1,
      4,
      1,
      10,
      4,
      9,
      21,
      17,
      3,
      5,
      6,
      8,
      6,
      6,
      1,
      0
    ]
  },
  {
    "name": "Toys & Kids",
    "color": "oklch(0.55 0.17 290)",
    "points": [
      0,
      2,
      9,
      5,
      4,
      2,
      3,
      5,
      0,
      6,
      12,
      8,
      14,
      6,
      8,
      0
    ]
  },
  {
    "name": "Pet Supplies",
    "color": "oklch(0.60 0.20 320)",
    "points": [
      0,
      3,
      3,
      4,
      5,
      3,
      7,
      5,
      0,
      2,
      5,
      5,
      6,
      8,
      0,
      0
    ]
  }
];
  const Q11_TOOLS        = [
  {
    "vn": "FBA",
    "name": "FBA",
    "count": 161,
    "use": 161,
    "satisfied": 48.3,
    "issues": 16.1
  },
  {
    "vn": "PPC/Ads",
    "name": "PPC/Ads",
    "count": 126,
    "use": 126,
    "satisfied": 35.3,
    "issues": 13.9
  },
  {
    "vn": "FBM",
    "name": "FBM",
    "count": 104,
    "use": 104,
    "satisfied": 27.0,
    "issues": 12.5
  },
  {
    "vn": "Inventory Management",
    "name": "Inventory Management",
    "count": 102,
    "use": 102,
    "satisfied": 24.5,
    "issues": 13.3
  },
  {
    "vn": "Amazon Support",
    "name": "Amazon Support",
    "count": 92,
    "use": 92,
    "satisfied": 20.2,
    "issues": 12.9
  },
  {
    "vn": "Helium 10",
    "name": "Helium 10",
    "count": 33,
    "use": 33,
    "satisfied": 6.6,
    "issues": 5.0
  },
  {
    "vn": "Seller Central",
    "name": "Seller Central",
    "count": 17,
    "use": 17,
    "satisfied": 3.1,
    "issues": 2.7
  },
  {
    "vn": "Brand Registry",
    "name": "Brand Registry",
    "count": 16,
    "use": 16,
    "satisfied": 2.6,
    "issues": 2.7
  },
  {
    "vn": "Jungle Scout",
    "name": "Jungle Scout",
    "count": 5,
    "use": 5,
    "satisfied": 0.7,
    "issues": 0.9
  },
  {
    "vn": "Amazon Vine",
    "name": "Amazon Vine",
    "count": 3,
    "use": 3,
    "satisfied": 0.4,
    "issues": 0.6
  }
];
  const Q11_ISSUES       = [
  {
    "vn": "Lỗi hệ thống / Bug",
    "name": "Lỗi hệ thống / Bug",
    "count": 471
  },
  {
    "vn": "Phí & chi phí cao",
    "name": "Phí & chi phí cao",
    "count": 125
  },
  {
    "vn": "Tài khoản bị khóa / suspend",
    "name": "Tài khoản bị khóa / suspend",
    "count": 122
  },
  {
    "vn": "Khó dùng / phức tạp",
    "name": "Khó dùng / phức tạp",
    "count": 84
  },
  {
    "vn": "Cập nhật chậm / outdated",
    "name": "Cập nhật chậm / outdated",
    "count": 13
  },
  {
    "vn": "Hỗ trợ chậm / kém",
    "name": "Hỗ trợ chậm / kém",
    "count": 10
  },
  {
    "vn": "Thiếu tính năng",
    "name": "Thiếu tính năng",
    "count": 7
  },
  {
    "vn": "Dữ liệu sai / không chính xác",
    "name": "Dữ liệu sai / không chính xác",
    "count": 2
  }
];
  const Q11_SATISFACTION = [
  {
    "vn": "Giá hợp lý / đáng tiền",
    "name": "Giá hợp lý / đáng tiền",
    "count": 267
  },
  {
    "vn": "Hiệu quả rõ rệt",
    "name": "Hiệu quả rõ rệt",
    "count": 234
  },
  {
    "vn": "Dễ dùng / trực quan",
    "name": "Dễ dùng / trực quan",
    "count": 201
  },
  {
    "vn": "Tiết kiệm thời gian",
    "name": "Tiết kiệm thời gian",
    "count": 119
  },
  {
    "vn": "Dữ liệu chính xác",
    "name": "Dữ liệu chính xác",
    "count": 84
  },
  {
    "vn": "Cộng đồng & tài liệu tốt",
    "name": "Cộng đồng & tài liệu tốt",
    "count": 56
  },
  {
    "vn": "Hỗ trợ tận tình",
    "name": "Hỗ trợ tận tình",
    "count": 26
  },
  {
    "vn": "Nhiều tính năng / đầy đủ",
    "name": "Nhiều tính năng / đầy đủ",
    "count": 10
  }
];
  const Q12_SERVICES   = [
  {
    "vn": "Accountant/Tax",
    "name": "Accountant/Tax",
    "count": 2357,
    "mentions": 2357,
    "need": 825,
    "satisfaction": 95,
    "demand": 707
  },
  {
    "vn": "Freight Forwarder",
    "name": "Freight Forwarder",
    "count": 1124,
    "mentions": 1124,
    "need": 393,
    "satisfaction": 82,
    "demand": 337
  },
  {
    "vn": "Software/Tools",
    "name": "Software/Tools",
    "count": 356,
    "mentions": 356,
    "need": 125,
    "satisfaction": 67,
    "demand": 107
  },
  {
    "vn": "Product Sourcing",
    "name": "Product Sourcing",
    "count": 308,
    "mentions": 308,
    "need": 108,
    "satisfaction": 66,
    "demand": 92
  },
  {
    "vn": "Legal/Trademark",
    "name": "Legal/Trademark",
    "count": 190,
    "mentions": 190,
    "need": 66,
    "satisfaction": 64,
    "demand": 57
  },
  {
    "vn": "VA/Assistant",
    "name": "VA/Assistant",
    "count": 66,
    "mentions": 66,
    "need": 23,
    "satisfaction": 61,
    "demand": 20
  },
  {
    "vn": "Photography",
    "name": "Photography",
    "count": 27,
    "mentions": 27,
    "need": 9,
    "satisfaction": 61,
    "demand": 8
  },
  {
    "vn": "Listing Optimization",
    "name": "Listing Optimization",
    "count": 24,
    "mentions": 24,
    "need": 8,
    "satisfaction": 60,
    "demand": 7
  }
];
  const Q13_COURSES    = [
  {
    "vn": "General Training",
    "name": "General Training",
    "count": 94,
    "mentions": 94,
    "seeking": 56,
    "interest": 53,
    "positive": 52,
    "negative": 9
  },
  {
    "vn": "Mentorship/Coaching",
    "name": "Mentorship/Coaching",
    "count": 18,
    "mentions": 18,
    "seeking": 11,
    "interest": 51,
    "positive": 10,
    "negative": 2
  },
  {
    "vn": "Amazon FBA Course",
    "name": "Amazon FBA Course",
    "count": 3,
    "mentions": 3,
    "seeking": 2,
    "interest": 50,
    "positive": 2,
    "negative": 0
  }
];
  const Q14_GROWTH     = [
  {
    "name": "Team Building",
    "count": 492,
    "color": "oklch(0.55 0.17 260)",
    "seeking": 271,
    "positive": 89,
    "mixed": 84,
    "negative": 49
  },
  {
    "name": "Automation & Tools",
    "count": 442,
    "color": "oklch(0.62 0.15 155)",
    "seeking": 243,
    "positive": 80,
    "mixed": 75,
    "negative": 44
  },
  {
    "name": "Scaling Operations",
    "count": 378,
    "color": "oklch(0.75 0.17 60)",
    "seeking": 208,
    "positive": 68,
    "mixed": 64,
    "negative": 38
  },
  {
    "name": "Market Expansion",
    "count": 226,
    "color": "oklch(0.62 0.15 200)",
    "seeking": 124,
    "positive": 41,
    "mixed": 38,
    "negative": 23
  },
  {
    "name": "Marketing & Ads",
    "count": 96,
    "color": "oklch(0.55 0.17 290)",
    "seeking": 53,
    "positive": 17,
    "mixed": 16,
    "negative": 10
  },
  {
    "name": "Revenue Growth",
    "count": 14,
    "color": "oklch(0.60 0.20 25)",
    "seeking": 8,
    "positive": 3,
    "mixed": 2,
    "negative": 1
  }
];
  return {
    Q7_TOPICS, Q7_BENEFITS, Q7_SENTIMENT,
    Q8_TRIGGERS, Q8_PERSONA, Q8_TREND,
    Q9_BARRIERS,
    Q10_TOP, Q10_WEEKS, Q10_WEEKLY,
    Q11_TOOLS, Q11_ISSUES, Q11_SATISFACTION,
    Q12_SERVICES, Q13_COURSES, Q14_GROWTH,
  };
})();
